### ISSUE TITLE
Unable to query PowerDNS API when using NGINX with PowerDNS-Admin

### ISSUE THREAD

**Issue by 2stacks** [PowerDNS-Admin/PowerDNS-Admin#1005]
Not sure if this is an NGINX issue or a PowerDNS-Admin issue.  When following the install/setup instructions for Debian/Ubuntu and [Running PowerDNS Admin with Systemd, Gunicorn and Nginx](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx), queries to the API fail with an `Internal Server Error`.  Tested with and without TLS enabled.  Failure is the same for both.

```
curl -H "X-API-Key: ${PDNS_API_KEY}" ${PDNS_API_URL}/api/v1/servers/localhost/zones
{"msg":"Internal Server Error"}
```
Log messages on server running PowerDNS-Admin
```
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]: [2021-09-27 05:58:40,048] [app.py:1892] ERROR - Exception on /api/v1/servers/localhost/zones [GET]
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]: Traceback (most recent call last):
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:   File "/opt/web/powerdns-admin/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:     response = self.full_dispatch_request()
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:   File "/opt/web/powerdns-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:     rv = self.handle_user_exception(e)
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:   File "/opt/web/powerdns-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:     reraise(exc_type, exc_value, tb)
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:   File "/opt/web/powerdns-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:     raise value
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:   File "/opt/web/powerdns-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:     rv = self.dispatch_request()
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:   File "/opt/web/powerdns-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:   File "/opt/web/powerdns-admin/powerdnsadmin/decorators.py", line 269, in decorated_function
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]:     apikey_val = str(base64.b64decode(auth_header), 'utf-8')
Sep 27 05:58:40 pub-dns-1 gunicorn[2529]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 0: invalid start byte
```

Bypassing NGINX and Gunicorn works as expected.

**Comment by jbe-dw** [comment]
I'm not really sure because it's a bit old but you have to be aware that the API Key must be base64 encoded. Someone provided a patch to allow apikey edition through the GUI and the patch outputs the base64 encoded version. The API has been updated to behave like this too.

This way users don't have to encode the key it's ready to use.

I confirm that the error is because it can't b64 decode the key.

**Comment by famaserver** [comment]
Hello
I have the same problem as this.
After installing pdns and its services, all services are properly active
But after the web server is working properly, the pdns panel is not loaded.
All services are active, including:
nginx
pdns
  powerdns-admin.socket
powerdns-admin.service

But the admin panel does not open with port 9191.
