### ISSUE TITLE
Drop pyOpenSSL dependency

### ISSUE THREAD

**Issue by zoeller-freinet** [PowerDNS-Admin/PowerDNS-Admin#1086]
https://pypi.org/project/pyOpenSSL/ states:

> Note: The Python Cryptographic Authority strongly suggests the use of pyca/cryptography where possible. If you are using pyOpenSSL for anything other than making a TLS connection you should move to cryptography and drop your pyOpenSSL dependency.

pyOpenSSL depends on [pyca/cryptography](https://pypi.org/project/cryptography/) itself. In PowerDNS-Admin, pyOpenSSL is only used inside [`lib.certutil`](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/7808febad8fb0a56cdecce2d7cdb9a92ec30ff06/powerdnsadmin/lib/certutil.py); `check_certificate` is never called and `create_self_signed_cert` does nothing that couldn't be done with `cryptography`.

**Comment by larsl-net** [comment]
Hi @zoeller-freinet,

Is this problem already being worked on?

I recently started getting the following error when logging in with SAML, which is probably fixed by this issue.
```
[2022-01-17 10:38:41,907] [app.py:1891] ERROR - Exception on /saml/login [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/powerdnsadmin/routes/index.py", line 936, in saml_login
    auth = saml.init_saml_auth(req)
  File "/app/powerdnsadmin/services/saml.py", line 125, in init_saml_auth
    create_self_signed_cert()
  File "/app/powerdnsadmin/lib/certutil.py", line 39, in create_self_signed_cert
    cert.gmtime_adj_notBefore(0)
  File "/usr/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1320, in gmtime_adj_notBefore
    notBefore = _lib.X509_get_notBefore(self._x509)
AttributeError: module 'lib' has no attribute 'X509_get_notBefore'
```
