### ISSUE TITLE
ImportError: cannot import name 'json' from 'itsdangerous'

### ISSUE THREAD

**Issue by trinv** [PowerDNS-Admin/PowerDNS-Admin#1125]
Stuck with this issue:
- Ubuntu 20.04
- PowerDNS4

(flask) root@ns1:/opt/web/powerdns-admin# export FLASK_APP=powerdnsadmin/__init__.py
(flask) root@ns1:/opt/web/powerdns-admin# flask db upgrade
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/itsdangerous/__init__.py)

**Comment by tooeffayy** [comment]
itsdangerous just updated to 2.1.0 which deprecates the json part. If you add itsdangerous==2.0.1 to requirements.txt, it will pin the version until the issue is actually fixed.
