### ISSUE TITLE
500 error when creating an API key

### ISSUE THREAD

**Issue by dmgeurts** [PowerDNS-Admin/PowerDNS-Admin#1141]
The service log shows the following:

sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1146, "Table 'pdns.apikey_account' doesn't exist")

How do I create this table, and why wasn't it there when I installed pdns-admin a couple of months ago? I guess the first question will be easier to answer than the latter.

**Comment by jbe-dw** [comment]
Hello,

We need to improve documentation and especially release notes. There are patches that add functionalities and you need to trigger migrations when updating the codebase.

Can you close the issue if the problem is solved ?

**Comment by vmarkop** [comment]
A db migration can be triggered by running `flask db upgrade`.

**Comment by jbe-dw** [comment]
Hello,

Can you give us a feedback about this issue ? Is it fixed by running the db upgrade ? 

Thank you.

**Comment by dmgeurts** [comment]
> flask db upgrade

Hi, that command fails for me:

```
me@host:~$ cd /var/www/html/pdns/
me@host:/var/www/html/pdns$ sudo -s
me@host:/var/www/html/pdns# source ./flask/bin/activate
(flask) root@host:/var/www/html/pdns# export FLASK_CONF=./configs/production.py
(flask) root@host:/var/www/html/pdns# export FLASK_APP=./powerdnsadmin/__init__.py
(flask) root@host:/var/www/html/pdns# flask db upgrade
Usage: flask db upgrade [OPTIONS] [REVISION]
Try 'flask db upgrade --help' for help.

Error: Could not import "powerdnsadmin.__init__".
```

I guess I'm still doing something wrong?

**Comment by jbe-dw** [comment]
The message says it tries to load `powerdnsadmin.__init__` while the you used `export FLASK_APP=./powerdnsadmin/__init__.py`. Can you do `ls $FLASK_APP` to check if the var has the extension and the file is reachable ?

You can add quote arround the value ?
You can try this oneline as well: `FLASK_APP=powerdnsadmin/__init__.py flask db upgrade` or `FLASK_APP="powerdnsadmin/__init__.py" flask db upgrade`

Regards

**Comment by dmgeurts** [comment]
Sure, here you go:

```
(flask) root@host:/var/www/html/pdns# ls -l $FLASK_APP
-rwxr-xr-x 1 root root 4275 Mar 14 16:15 ./powerdnsadmin/__init__.py
```

Removing the './' from FLASK_APP results in the following error:

```
(flask) root@host:/var/www/html/pdns# export FLASK_CONF=./configs/production.py
(flask) root@host:/var/www/html/pdns# export FLASK_APP=powerdnsadmin/__init__.py
(flask) root@host:/var/www/html/pdns# flask db upgrade
Traceback (most recent call last):
  File "/var/www/html/pdns/flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/var/www/html/pdns/powerdnsadmin/__init__.py", line 70, in create_app
    app.config.from_envvar('FLASK_CONF')
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/config.py", line 111, in from_envvar
    return self.from_pyfile(rv, silent=silent)
  File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/config.py", line 131, in from_pyfile
    with open(filename, mode="rb") as config_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/var/www/html/pdns/powerdnsadmin/./configs/production.py'
```

The right path for that file is `/var/www/html/pdns/configs/production.py`, but how do I fix the reference?

**Comment by jbe-dw** [comment]
The configuration path should be relative to the app or absolute. 

Can you try `export FLASK_CONF=../configs/production.py` or `export FLASK_CONF=/var/www/html/pdns/configs/production.py` ?

**Comment by dmgeurts** [comment]
Ahh, I had used `../` on both exports instead of `./` before but that didn't work. This did:

```
(flask) root@host:/var/www/html/pdns# export FLASK_CONF=../configs/production.py
(flask) root@host:/var/www/html/pdns# export FLASK_APP=powerdnsadmin/__init__.py
(flask) root@host:/var/www/html/pdns# flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
INFO  [alembic.runtime.migration] Running upgrade 59729e468045 -> 1274ed462010, Change setting.value data type
INFO  [alembic.runtime.migration] Running upgrade 1274ed462010 -> 4a666113c7bb, Adding Operator Role
INFO  [alembic.runtime.migration] Running upgrade 4a666113c7bb -> 31a4ed468b18, Remove all setting in the DB
INFO  [alembic.runtime.migration] Running upgrade 31a4ed468b18 -> 654298797277, Upgrade DB Schema
INFO  [alembic.runtime.migration] Running upgrade 654298797277 -> 0fb6d23a4863, Remove user avatar
INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
INFO  [alembic.runtime.migration] Running upgrade 856bb94b7040 -> b0fea72a3f20, Update domain serial columns type
INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column
INFO  [alembic.runtime.migration] Running upgrade 3f76448bb6de -> 0d3d93f1c2e0, Add domain_id to history table
INFO  [alembic.runtime.migration] Running upgrade 0d3d93f1c2e0 -> 0967658d9c0d, add apikey account mapping table
```

**Comment by dmgeurts** [comment]
Strangely enough, the issue is back after a git pull to update pdnsadmin. flask db upgrade ran without issue, but I'm getting the following error `MySQLdb._exceptions.ProgrammingError: (1146, "Table 'pwrdns.apikey_account' doesn't exist")`

How do I create this table and what other tables might I be missing?

Full error here:
```
Oct 10 12:58:32 host.domain.com gunicorn[34601]: [2022-10-10 12:58:32,539] [app.py:1891] ERROR - Exception on /admin/manage-keys [GET]
Oct 10 12:58:32 host.domain.com gunicorn[34601]: Traceback (most recent call last):
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     self.dialect.do_execute(
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     cursor.execute(statement, parameters)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     res = self._query(query)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     db.query(q)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     _mysql.connection.query(self, query)
Oct 10 12:58:32 host.domain.com gunicorn[34601]: MySQLdb._exceptions.ProgrammingError: (1146, "Table 'pwrdns.apikey_account' doesn't exist")
Oct 10 12:58:32 host.domain.com gunicorn[34601]: The above exception was the direct cause of the following exception:
Oct 10 12:58:32 host.domain.com gunicorn[34601]: Traceback (most recent call last):
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     response = self.full_dispatch_request()
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     rv = self.handle_user_exception(e)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     reraise(exc_type, exc_value, tb)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     raise value
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     rv = self.dispatch_request()
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return self.view_functions[rule.endpoint](**req.view_args)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return func(*args, **kwargs)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/decorators.py", line 33, in decorated_function
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return f(*args, **kwargs)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/routes/admin.py", line 395, in manage_keys
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return render_template('admin_manage_keys.html',
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return _render(
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     rv = template.render(context)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     self.environment.handle_exception()                                                                                                        Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     raise rewrite_traceback_stack(source=source)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/templates/admin_manage_keys.html", line 2, in top-level template code
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     {% set active_page = "admin_keys" %}
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/templates/base.html", line 192, in top-level template code
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     {% block content %}
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/templates/admin_manage_keys.html", line 49, in block 'content'
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     <td>{% for account in key.accounts %}{{ account.name }}{% if not loop.last %}, {% endif %}{% endfor %}</td>
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return getattr(obj, attribute)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 287, in __get__
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return self.impl.get(instance_state(instance), dict_)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 723, in get
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     value = self.callable_(state, passive)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 759, in _load_for_state
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return self._emit_lazyload(
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "<string>", line 1, in <lambda>
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 900, in _emit_lazyload
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     q(session)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 545, in all
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return list(self)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 445, in __iter__
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return q._execute_and_instances(context)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     result = conn.execute(querycontext.statement, self._params)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return meth(self, multiparams, params)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     return connection._execute_clauseelement(self, multiparams, params)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     ret = self._execute_context(
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     self._handle_dbapi_exception(
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     util.raise_(
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     raise exception
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     self.dialect.do_execute(
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     cursor.execute(statement, parameters)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     res = self._query(query)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     db.query(q)
Oct 10 12:58:32 host.domain.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
Oct 10 12:58:32 host.domain.com gunicorn[34601]:     _mysql.connection.query(self, query)
Oct 10 12:58:32 host.domain.com gunicorn[34601]: sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1146, "Table 'pwrdns.apikey_account' doesn't exist")
Oct 10 12:58:32 host.domain.com gunicorn[34601]: [SQL: SELECT account.id AS account_id, account.name AS account_name, account.description AS account_description, account.contact AS account_con
tact, account.mail AS account_mail
Oct 10 12:58:32 host.domain.com gunicorn[34601]: FROM account, apikey_account
Oct 10 12:58:32 host.domain.com gunicorn[34601]: WHERE %s = apikey_account.apikey_id AND account.id = apikey_account.account_id]
Oct 10 12:58:32 host.domain.com gunicorn[34601]: [parameters: (3,)]
Oct 10 12:58:32 host.domain.com gunicorn[34601]: (Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by dmgeurts** [comment]
Found this code, so now resorting to manually creating the table. But for the foreign key options, which should be used? cascade, restrict, no action, or set null?

```def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apikey_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['apikey_id'], ['apikey.id'], ),
    sa.PrimaryKeyConstraint('id')
```

**Comment by dmgeurts** [comment]
But after creating the table manually I get a code error: 

```
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]: [2022-10-10 13:28:22,397] [app.py:1891] ERROR - Exception on /dashboard/ [GET]
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]: Traceback (most recent call last):
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     response = self.full_dispatch_request()
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     rv = self.handle_user_exception(e)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     reraise(exc_type, exc_value, tb)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     raise value
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     rv = self.dispatch_request()
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     return self.view_functions[rule.endpoint](**req.view_args)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     return func(*args, **kwargs)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/routes/dashboard.py", line 192, in dashboard
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     detailedHistories = convert_histories(history)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/routes/admin.py", line 915, in convert_histories
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     detailedHistories.append(DetailedHistory(histories[i], None))
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/var/www/html/pdns/powerdnsadmin/routes/admin.py", line 767, in __init__
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     detail_dict = json.loads(history.detail)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     return _default_decoder.decode(s)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]:     obj, end = self.scan_once(s, idx)
Oct 10 13:28:22 web07.ixbru.ipnexia.com gunicorn[34601]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Comment by dmgeurts** [comment]
This post saved my bacon: https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1229#issuecomment-1255711518

I think the DB update stuff after a code update needs a little more work...

**Comment by dmgeurts** [comment]
For those coming here trying to fix similar stuff: It appears that doing an apt upgrade updates PowerDNS without adding the extra columns into the database: https://doc.powerdns.com/authoritative/backends/generic-mysql.html

So make sure to check the PowerDNS logs as well as if PowerDNS returns a 500 error via the API then pdns-admin passes it up the chain. So don't always assume it's pdns-admin that's the cause of the 500 error.
