### ISSUE TITLE
Problem with some python dependencies 

### ISSUE THREAD

**Issue by PauloHeaven** [PowerDNS-Admin/PowerDNS-Admin#1150]
Hi,

I just cloned the latest version of PDA. At the `flask db upgrade` step, here is what happens:

`(venv) root@arnage:/opt/web/powerdns-admin# flask db upgrade
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/venv/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/werkzeug/wrappers/__init__.py)`

After some googling, it appears that you use a deprecated feature (in the name of BaseResponse) from the werkzeug package. So I reinstalled it in version 2.0. Well, but then, this happens:

```(venv) root@arnage:/opt/web/powerdns-admin# flask db upgrade
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/opt/web/powerdns-admin/powerdnsadmin/__init__.py", line 70, in create_app
    app.config.from_envvar('FLASK_CONF')
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/config.py", line 111, in from_envvar
    return self.from_pyfile(rv, silent=silent)
  File "/opt/web/powerdns-admin/venv/lib/python3.8/site-packages/flask/config.py", line 132, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "/opt/web/powerdns-admin/powerdnsadmin/../configs/production.py", line 21, in <module>
    urllib.parse.quote_plus(SQLA_DB_USER),
NameError: name 'urllib' is not defined```

I don't know what more to try and nobody appears to run into this issue. I run Ubuntu 20.04, every package is up to date.

Thank you by advance

**Comment by eLvErDe** [comment]
Hello,

It's seems you messed up `production.py` file. Just add `import urllib.parse` on the beggining of the file with other imports and that should be okay.

Regards

**Comment by vmarkop** [comment]
Hello! You are right, yesterday werkzeug was updated to [3.1.0 ](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0), dropping support for Python 3.6.

However, pinning the latest working version (2.0.3) in the requirements.txt file fixes the problem. We could not reproduce the second issue you mentioned. It is possible that @eLvErDe 's solution fixes your problem, please let us know otherwise.

We will now update the requirements to pin werkzeug version 2.0.3.

**Comment by PauloHeaven** [comment]
Hello,

Thank you for your reactivity. There is a `import urllib.parse` line in the production.py file that I didn't notice, and it was commented out. My last installation of PDA traces back to about 2 years ago, many parts of this file changed and that wasn't needed before. I was finally able to compile the assets.
