### ISSUE TITLE
Using " ' as username for login breaks dashboard 

### ISSUE THREAD

**Issue by AdvanticGmbH** [PowerDNS-Admin/PowerDNS-Admin#1156]
```
|  1 | User "" authentication failed       | {'username': '""', 'authenticator': 'LOCAL', 'ip_address': '', 'success': 0}    | System     | 2022-04-04 10:57:08 |      NULL |
```

```
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]: [2022-04-04 12:51:14,912] [app.py:1892] ERROR - Exception on /dashboard/ [GET]
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]: Traceback (most recent call last):
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 2447
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     response = self.full_dispatch_request()
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1952
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     rv = self.handle_user_exception(e)
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1821
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     reraise(exc_type, exc_value, tb)
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/_compat.py", line 
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     raise value
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1950
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     rv = self.dispatch_request()
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1936
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask_login/utils.py", l
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     return func(*args, **kwargs)
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/dashboard.py", line 192, in dashboar
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     detailedHistories = convert_histories(history)
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 907, in convert_hist
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     detailedHistories.append(DetailedHistory(histories[i], None))
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 769, in __init__
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     detail_dict = json.loads(history.detail.replace("'", '"'))
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     return _default_decoder.decode(s)
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:   File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]:     obj, end = self.scan_once(s, idx)
Apr 04 12:51:14 nictool.in.advantic.de gunicorn[25132]: json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 16 (char 15)
```

**Comment by jbe-dw** [comment]
@AdvanticGmbH is this issue resolved by your patch ?

**Comment by jbe-dw** [comment]
it is. I close
