### ISSUE TITLE
API key generation error

### ISSUE THREAD

**Issue by huglester** [PowerDNS-Admin/PowerDNS-Admin#1170]
Hey

when generating api key, I get

```
[2022-04-17 06:46:44,263] [app.py:1891] ERROR - Exception on /admin/key/edit [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/powerdns-admin/powerdnsadmin/decorators.py", line 32, in decorated_function
    return f(*args, **kwargs)
  File "/opt/powerdns-admin/powerdnsadmin/routes/admin.py", line 340, in edit_key
    apikey = ApiKey(desc=description,
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 432, in _initialize_instance
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/opt/powerdns-admin/powerdnsadmin/models/api_key.py", line 36, in __init__
    self.key = self.get_hashed_password(rand_key).decode('utf-8')
  File "/opt/powerdns-admin/powerdnsadmin/models/api_key.py", line 110, in get_hashed_password
    current_app.config.get('SALT').encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by vmarkop** [comment]
Hello,

It looks like your Salt value is None.

You may have not specified Salt in your Basic App Config, in file development.py.

Please try generating a new valid Salt value, using
`python3 -c 'import bcrypt;print( bcrypt.gensalt() );'`

Then add SALT = the value generated above in the /configs/development.py file.

Finally, restart the application, making sure to perform this:
`export FLASK_CONF=../configs/production.py`
OR
`export FLASK_CONF=../configs/development.py`, depending on which config file you are using,
before running.

Please let us know if the problem persists.
