### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by ntinti** [PowerDNS-Admin/PowerDNS-Admin#1192]
Don't know why, but after upgrading from python 3.6 to 3.8 and newest powerdns-admin master I can't edit any existing domain anymore. "TypeError: list indices must be integers or slices, not str"
Something in the settings functions "get_records_allow_to_edit" and "get_forward_records_allow_to_edit" seems to get wrong.

```
[2022-05-15 02:42:45,099] [app.py:1891] ERROR - Exception on /domain/x.de [GET]
Traceback (most recent call last):
...
  File "/usr/local/www/PowerDNS-Admin/powerdnsadmin/decorators.py", line 74, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/www/PowerDNS-Admin/powerdnsadmin/routes/domain.py", line 73, in domain
    records_allow_to_edit = Setting().get_records_allow_to_edit()
  File "/usr/local/www/PowerDNS-Admin/powerdnsadmin/models/setting.py", line 293, in get_records_allow_to_edit
    set(self.get_forward_records_allow_to_edit() +
  File "/usr/local/www/PowerDNS-Admin/powerdnsadmin/models/setting.py", line 300, in get_forward_records_allow_to_edit
    r_name = [r for r in f_records if f_records[r]]
  File "/usr/local/www/PowerDNS-Admin/powerdnsadmin/models/setting.py", line 300, in <listcomp>
    r_name = [r for r in f_records if f_records[r]]
TypeError: list indices must be integers or slices, not str
```

**Comment by jbe-dw** [comment]
Hello,

It looks like your setting is not returning a list. Can you add these line just before L300:
`current_app.logger.debug("{} => {}".format(records, f_records))`

and paste the content of the debug output here (just relevant lines, like the one crashing and one or two before) ? (it will be logged just before the stack trace)

Regards
