### ISSUE TITLE
PDA Project Update

### ISSUE THREAD

**Issue by AzorianSolutions** [PowerDNS-Admin/PowerDNS-Admin#1318]
# PDA Project Update

## Introduction

Hello PDA community members,

My name is Matt Scott, and I am the owner of [Azorian Solutions](https://azorian.solutions), a consultancy for the
Internet Service Provider (ISP) industry. I'm pleased to announce that I have taken ownership of the PDA project and
will be taking over the lead maintainer role, effective immediately.

Please always remember and thank both [Khanh Ngo](https://github.com/ngoduykhanh) and
[Jérôme Becot](https://github.com/jbe-dw) for their efforts in keeping this project alive thus far. Without the effort
of Khanh creating the PDA project and community, and the efforts of Jérôme for holding up the lead maintainer role after
Khanh had to step down, this project would not still be alive today.

With that being said, please read through all the following announcements as they are important if you're an active PDA
user or community member. I intend to make many great enhancements to the project, but it could be a bumpy road ahead.

### Project Maintenance

As it stands today, contributions to the project are at a low. At this point, there is a rather large backlog of issues
and feature requests in contrast to the current maintenance capacities. This is not to say you should lose hope though!
As part of this project transition, some additional contribution interest has been generated and I expect to attract
more with the changes I'm planning to make. In the near future, I may by-pass some usual maintenance processes in order
to expedite some changes to the project that have been outstanding for some time.

This is to say however that unless the project attracts a healthy new contribution base, issues may continue to pile up
as maintenance capacity is rather limited. This is further complicated by the fact that the current code base is harder
to follow naturally since it largely lacks uniformity and standards. This lack of uniformity has lead to a difficult
situation that makes implementing certain changes less effective. This status quo is not uncommon with projects born how
PDA was born, so it's unfortunate but not unexpected.

### Change of Direction

In order to reorganize the project and get it on a track to a future that allows it to contend with other commercial
quality products, I had to make many considerations to the proficiencies of two unique paths forward to achieve this
goal. One path forward is seemingly obvious, continue maintaining the current code base while overhauling it to shift it
towards the envisioned goal. The other path is a fresh solution design with a complete rebuild.

The answer to the aforementioned decision might seem obvious to those of you who typically favor the "don't reinvent the
wheel" mentality. I'm unclear of the details surrounding the original use-case that drove the development of this
project, but I don't believe it was on-par with some use-cases we see today which include operators handling many tens
of thousands of zones and/or records. There are many changes that have been (sometimes) haphazardly implemented which
has lead to the previously mentioned lack of uniformity among other issues. To put it simply, I'm not sure if the
project ever had a grand vision per se but instead was mostly reactionary to community requests.

I believe that the current project has served the community fairly well from what I can tell. I know the product has
certainly helped me in my professional efforts with many environments. I also believe that it's time to pivot so that
the project can realize it's true potential, considering the existing user base. For this reason, I am beginning the
planning phase of a project overhaul. This effort will involve a complete re-engineering of the project's contribution
standards and requirements, technology stack, and project structure.

This was not an easy decision to come to but one must appreciate that there aren't as many people that can get very
excited about working on the current project code base. The current project has many barriers to entry which I intend to
drastically impact with future changes. The reality is that it's easier to gain contribution participation with a new
build effort as it offers an opportunity to own a part of the project with impactful contributions. 

### Project Enhancements

Since this is the beginning of a rebirth of the project so to speak, I want to implement a new operational tactic that
will hopefully drive contributions through incentive. Many of us understand that any project, needs a leader to stay on
track and organized. If everything were a democratic process, it would take too long of suffer unnecessary challenges.
With that being said, I do believe that there is plenty of opportunity through-out various development phases of the
project to allow for a democratic process where the community contributors and members can participate in the
decision-making.

The plan to achieve the aforementioned democratic goal is to centralize communications and define some basic structured
processes. To do this, more effective methods of communication have been implemented to allow those interested in
contributing to easily participate in fluid, open communication. This has already been proving to be quite effective for
exchanging ideas and visions while addressing the issue with contributors living in vastly different time zones. This is
effectively a private chat hosted by the PDA project using Mattermost (a Slack-like alternative).

Even if you aren't in a position to directly contribute work to the project, you can still contribute by participating
in these very important and early discussions that will impact the solution engineering. If the PDA project is an
important tool in your organization, I encourage you to join the conversation and contribute where applicable your
views. More information on the community use-cases will only benefit the future of this project.

If you're interested in joining the conversation, please email me at
[admin@powerdnsadmin.org](mailto:admin@powerdnsadmin.org) for an invitation.

### Rebranding

As part of this project transition, I will also be changing the naming scheme in order to support the future development
efforts toward a newly engineered solution. The current PDA project will ultimately become known as the "PDA Legacy"
application. This change will help facilitate the long-term solution to take the branding position of the existing
solution. Another effort I will be making is to get an app landing page online at the project's new domain:
[powerdnsadmin.org](https://powerdnsadmin.org). This will act as one more point of online exposure for the project which
will hopefully lend itself well to attracting additional community members.

### Contribution Requirements

Another big change that will be made with the new project, will be well-defined contribution requirements. I realize
these requirements can be demotivating for some, but they are a necessary evil to ensure the project actually achieves
its goals effectively. It's important to always remember that strict requirements are to everyone's benefit as they push
for order where chaos is quite destructive.

### Closing

I hope these announcements garner more participation in the PDA community. The project definitely needs more help to
achieve any goal at this point, so your participation is valued!

**Comment by MikEarpp** [comment]
Thank you very much for your sharing
<details>
  <summary>I keep version 0.3.3</summary>
  
2022-12-10T13:57:24.172481700Z Traceback (most recent call last):
2022-12-10T13:57:24.172554727Z   File "/usr/bin/flask", line 8, in <module>
2022-12-10T13:57:24.172564670Z     sys.exit(main())
2022-12-10T13:57:24.172570075Z   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 967, in main
2022-12-10T13:57:24.172608053Z     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
2022-12-10T13:57:24.172613922Z   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 586, in main
2022-12-10T13:57:24.172619290Z     return super(FlaskGroup, self).main(*args, **kwargs)
2022-12-10T13:57:24.172624622Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1055, in main
2022-12-10T13:57:24.172629800Z     rv = self.invoke(ctx)
2022-12-10T13:57:24.172634687Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2022-12-10T13:57:24.172647229Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-12-10T13:57:24.172652343Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2022-12-10T13:57:24.172657829Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-12-10T13:57:24.172662652Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2022-12-10T13:57:24.172667549Z     return ctx.invoke(self.callback, **ctx.params)
2022-12-10T13:57:24.172672366Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2022-12-10T13:57:24.172677254Z     return __callback(*args, **kwargs)
2022-12-10T13:57:24.172700465Z   File "/usr/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
2022-12-10T13:57:24.172705959Z     return f(get_current_context(), *args, **kwargs)
2022-12-10T13:57:24.172711091Z   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
2022-12-10T13:57:24.172716196Z     return __ctx.invoke(f, *args, **kwargs)
2022-12-10T13:57:24.172721198Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2022-12-10T13:57:24.172726278Z     return __callback(*args, **kwargs)
2022-12-10T13:57:24.172731224Z   File "/usr/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
2022-12-10T13:57:24.172736286Z     _upgrade(directory, revision, sql, tag, x_arg)
2022-12-10T13:57:24.172741411Z   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
2022-12-10T13:57:24.172746480Z     f(*args, **kwargs)
2022-12-10T13:57:24.172751392Z   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 271, in upgrade
2022-12-10T13:57:24.172756480Z     command.upgrade(config, revision, sql=sql, tag=tag)
2022-12-10T13:57:24.172761402Z   File "/usr/lib/python3.8/site-packages/alembic/command.py", line 322, in upgrade
2022-12-10T13:57:24.172766608Z     script.run_env()
2022-12-10T13:57:24.172771431Z   File "/usr/lib/python3.8/site-packages/alembic/script/base.py", line 569, in run_env
2022-12-10T13:57:24.172785198Z     util.load_python_file(self.dir, "env.py")
2022-12-10T13:57:24.172791906Z   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2022-12-10T13:57:24.172797223Z     module = load_module_py(module_id, path)
2022-12-10T13:57:24.172802034Z   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2022-12-10T13:57:24.172807077Z     spec.loader.exec_module(module)  # type: ignore
2022-12-10T13:57:24.172811925Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2022-12-10T13:57:24.172817027Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-12-10T13:57:24.172822118Z   File "migrations/env.py", line 88, in <module>
2022-12-10T13:57:24.172827152Z     run_migrations_online()
2022-12-10T13:57:24.172831941Z   File "migrations/env.py", line 68, in run_migrations_online
2022-12-10T13:57:24.172836851Z     engine = engine_from_config(config.get_section(config.config_ini_section),
2022-12-10T13:57:24.172841795Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 543, in engine_from_config
2022-12-10T13:57:24.172846848Z     return create_engine(url, **options)
2022-12-10T13:57:24.172851690Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
2022-12-10T13:57:24.172856863Z     return strategy.create(*args, **kwargs)
2022-12-10T13:57:24.172861648Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
2022-12-10T13:57:24.172866631Z     dbapi = dialect_cls.dbapi(**dbapi_args)
2022-12-10T13:57:24.172871500Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
2022-12-10T13:57:24.172876560Z     return __import__("MySQLdb")
2022-12-10T13:57:24.172890833Z ModuleNotFoundError: No module named 'MySQLdb'
  }
  ```

version: '3.9'
networks:
  minette:
    external: true
    internal: false
  nonette:
    external: true
    internal: true
services:

  pdns_admin:
    container_name: pdns_admin
    env_file:
      - .env
      - .env_mysql_pdns
    environment:
      SQLALCHEMY_DATABASE_URI: mysql://${_MYSQL_USER}:${_MYSQL_PASS}@${_NO_INTERNET_SUBNET_IP}${_MARIADB_IP}:${_MARIADB_PORT}/${_MYSQL_DB}
      GUNICORN_LOGLEVEL: DEBUG
    #image: ngoduykhanh/powerdns-admin:latest
    image: ngoduykhanh/powerdns-admin:v0.3.0
    networks:
      minette:
        ipv4_address: ${_DOCKER_SUBNET_IP}${_PDNS_WEB_IP}
      nonette:
        ipv4_address: ${_NO_INTERNET_SUBNET_IP}${_PDNS_WEB_IP}
    restart: unless-stopped
</details>

**Comment by AzorianSolutions** [comment]
@MikEarpp respectfully, this is not the place to open a support issue with the project as this is a formal announcement. Please create a new issue as a question or bug if you're seeking assistance. Thank you for being a user of PDA!

**Comment by ngoduykhanh** [comment]
Thanks @AzorianSolutions for taking the ownership of PowerDNS-Admin project. I hope you and the other maintainers will keep the project developing and bring value to the community. 👍 🥇 🎆

**Comment by nulluserid** [comment]
Thanks for taking over on this, and do let us know what can be done to help. Bug bounties? Testing? etc?

**Comment by AzorianMatt** [comment]
@nulluserid thank you for the sentiment.

There will always be room for additional help so if you're interested in participating, I recommend following the instructions in this announcement to receive an invite link to the private project chat where we can collaborate further on efforts!

**Comment by feldsam** [comment]
Hello @AzorianMatt , I tried to reach you on email admin@powerdnsadmin.org, but email returned with undelivery message:

```
The mail system

<[admin@powerdnsadmin.org](mailto:admin@powerdnsadmin.org)>: host mail.azorian.solutions[3.140.62.113] said: 450
   4.1.8 <[feldsam@feldhost.cz](mailto:feldsam@feldhost.cz)>: Sender address rejected: Domain not found (in
   reply to RCPT TO command)
Reporting-MTA: dns; [mail.feldhost.cz](http://mail.feldhost.cz/)
X-Postcow-Queue-ID: AB21A1EE0027
X-Postcow-Sender: rfc822; [feldsam@feldhost.cz](mailto:feldsam@feldhost.cz)
Arrival-Date: Mon,  6 Mar 2023 17:54:05 +0100 (CET)

Final-Recipient: rfc822; [admin@powerdnsadmin.org](mailto:admin@powerdnsadmin.org)
Original-Recipient: rfc822;[admin@powerdnsadmin.org](mailto:admin@powerdnsadmin.org)
Action: delayed
Status: 4.1.8
Remote-MTA: dns; mail.azorian.solutions
Diagnostic-Code: smtp; 450 4.1.8 <[feldsam@feldhost.cz](mailto:feldsam@feldhost.cz)>: Sender address
   rejected: Domain not found
Will-Retry-Until: Sat, 11 Mar 2023 17:54:05 +0100 (CET)
Return-Path: <[feldsam@feldhost.cz](mailto:feldsam@feldhost.cz)>
Received: from [127.0.0.1] (localhost [127.0.0.1]) by localhost (Mailerdaemon) with ESMTPSA id AB21A1EE0027
	for <[admin@powerdnsadmin.org](mailto:admin@powerdnsadmin.org)>; Mon,  6 Mar 2023 17:54:05 +0100 (CET)
```

**Comment by AzorianMatt** [comment]
@feldsam my apologies, give it a try now. I was experiencing some issues with my mail server in the recent days and thought it had everything squared away. Glad you said something!

**Comment by alsyundawy** [comment]
any update ?

**Comment by zarlo** [comment]
> any update ?

@alsyundawy there have been some pushes in the fast few says

**Comment by AzorianMatt** [comment]
> > any update ?
> 
> @alsyundawy there have been some pushes in the fast few says 

I plan to make a formal project update announcement in the near future. I want to hit a certain milestone on what I'm doing before I do so.

Thanks for taking notice!

**Comment by alsyundawy** [comment]
1-2 years still not active no like poweradmin hehehehe
