### ISSUE TITLE
bug: User update is broken

### ISSUE THREAD

**Issue by BluemediaGER** [PowerDNS-Admin/PowerDNS-Admin#1329]
Edit: This seems to affect any changes made to a user. When enabling 2FA in the user profile, for example, the same error occurs.

Login via OIDC currently seems to be broken using the latest Docker image. After being redirected from the IdP, PowerDNS-Admin fails to update the corresponding user object:
```
[2022-12-13 22:55:44,704] [app.py:1891] ERROR - Exception on /login [GET]
Traceback (most recent call last):
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
 File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/powerdnsadmin/routes/index.py", line 388, in login
    result = user.update_local_user()
  File "/app/powerdnsadmin/models/user.py", line 463, in update_local_user
   user.password = self.get_hashed_password(
AttributeError: 'NoneType' object has no attribute 'decode'
```

I tracked this issue down to commit 4fd1b1001847eaef73b3da9a222c011068a3b2b7. The new code uses `hasattr()` to check if `plain_text_password` exists:
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/4fd1b1001847eaef73b3da9a222c011068a3b2b7/powerdnsadmin/models/user.py#L461-L464
But `plain_text_password` always exists. It's `None` if not set otherwise. This leads to `hasattr()` always returning `True`, which in turn runs the code inside the if statement with invalid input.  

Calling `get_hashed_password()` returns `plain_text_password` if it's `None`. So effectively the function returns `None` in this case:
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/4fd1b1001847eaef73b3da9a222c011068a3b2b7/powerdnsadmin/models/user.py#L99-L106
This leads to `update_local_user()` effectively trying to call `None.decode()`.
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/4fd1b1001847eaef73b3da9a222c011068a3b2b7/powerdnsadmin/models/user.py#L463-L464

**Comment by caraar12345** [comment]
Just popping in here to say I've seen the same. Thanks for providing the commit that broke it - I can fight with that 👀
