### ISSUE TITLE
Error 500 on domains with xn-- (Cannot decode IDN domain)

### ISSUE THREAD

**Issue by SuperKumKum** [PowerDNS-Admin/PowerDNS-Admin#1336]
Hello,

I've just upgraded my pdns-admin instance from (last commit)  e89133397105e0cb27dff9222b0ce7ec9fb24d8d to the up-to-date master branch with commit 0404748e6e71851f28bc56f7ea2983eac83fac19

The main reason for the upgrade, is that when I tried to edit a domain with xn--, I've got this error:
`Failed to apply changes. Rolled back previous failed operation: Record xn--designrsine-hbb.be./MX 10 mail.designrésine.be.: Not in expected format (parsed as 10 mail.designr\195\169sine.be.)`

I saw that there was a fix at: https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1163

- Here are the logs of the error:

```
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]: [2022-12-19 15:39:12,212] [app.py:1892] ERROR - Exception on /domain/xn--commercevendre-ngb.be [GET]
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]: Traceback (most recent call last):
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/lib/utils.py", line 252, in pretty_domain_name
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     #                return to_idna(value, 'decode')
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/lib/utils.py", line 276, in to_idna
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     #                result.append(idna.decode(split))
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/idna/core.py", line 393, in decode
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     s = ulabel(label)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/idna/core.py", line 308, in ulabel
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     check_label(label)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/idna/core.py", line 261, in check_label
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))                                             
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]: idna.core.InvalidCodepoint: Codepoint U+0020 at position 3 of '10 mail' not allowed
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]: During handling of the above exception, another exception occurred:
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]: Traceback (most recent call last):
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     response = self.full_dispatch_request()
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     rv = self.handle_user_exception(e)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     reraise(exc_type, exc_value, tb)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise                                                                    
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     raise value
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     rv = self.dispatch_request()
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     return self.view_functions[rule.endpoint](**req.view_args)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     return func(*args, **kwargs)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/decorators.py", line 75, in decorated_function
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     return f(*args, **kwargs)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/routes/domain.py", line 136, in domain                                                                                       
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     current_user=current_user)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template                                                        
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     ctx.app,
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render                                                                
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     rv = template.render(context)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render                                                              
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     self.environment.handle_exception()
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     raise rewrite_traceback_stack(source=source)
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/templates/domain.html", line 1, in top-level template code
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     {% extends "base.html" %}
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/templates/base.html", line 192, in top-level template code
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     {% block content %}
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/templates/domain.html", line 82, in block 'content'
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     {{ record.data | pretty_domain_name }}
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:   File "/opt/powerdns-admin/powerdnsadmin/lib/utils.py", line 254, in pretty_domain_name
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]:     #                raise Exception('Cannot decode IDN domain')
Dec 19 15:39:12 pdnsadmin01 uwsgi[23386]: Exception: Cannot decode IDN domain
```

Got similar issue: https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1325

Tell me if you need more information about anything else.
Thanks in advance for your help.

**Comment by AzorianSolutions** [comment]
@SuperKumKum at this time, there are various known issues with the use of xn domain formats. Due to a lack of contributors, I can not provide an expectation on when this problem will be fully put to rest so to speak. I would like to have it handled by the 0.4.0 release, but no official date has been set for that at this time.

Thank you for the report.
