### ISSUE TITLE
URLLIB is not defined

### ISSUE THREAD

**Issue by shnacharya** [PowerDNS-Admin/PowerDNS-Admin#1360]
getting this below error during db migrate.

(venv) root@blr1-dns-01:/opt/web/powerdns-admin# flask db upgrade
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/opt/web/powerdns-admin/powerdnsadmin/__init__.py", line 44, in create_app
    app.config.from_envvar('FLASK_CONF')
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/config.py", line 111, in from_envvar
    return self.from_pyfile(rv, silent=silent)
  File "/opt/web/powerdns-admin/venv/lib/python3.9/site-packages/flask/config.py", line 132, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "/opt/web/powerdns-admin/powerdnsadmin/../configs/production.py", line 21, in <module>
    urllib.parse.quote_plus(SQLA_DB_USER),
NameError: name 'urllib' is not defined

**Comment by AzorianMatt** [comment]
@shnacharya, Given that this report lacks environmental context, basic formatting, and reproduction steps, I'm closing the issue.

**Comment by bekiroz** [comment]
same issue here

Traceback (most recent call last):
  File "/var/www/html/pdns/flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/cli.py", line 354, in decorator
    app = __ctx.ensure_object(ScriptInfo).load_app()
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/cli.py", line 235, in locate_app
    return find_best_app(module)
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/cli.py", line 63, in find_best_app
    app = app_factory()
  File "/var/www/html/pdns/powerdnsadmin/__init__.py", line 40, in create_app
    app.config.from_object('powerdnsadmin.default_config')
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/config.py", line 227, in from_object
    obj = import_string(obj)
  File "/var/www/html/pdns/flask/lib/python3.9/site-packages/werkzeug/utils.py", line 595, in import_string
    __import__(import_name)
  File "/var/www/html/pdns/powerdnsadmin/default_config.py", line 28, in <module>
    urllib.parse.quote_plus(SQLA_DB_USER),
NameError: name 'urllib' is not defined

**Comment by bekiroz** [comment]
solution
nano /var/www/html/pdns/powerdnsadmin/default_config.py

and comment out this lines its not needed
#SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@{}/{}'.format(
#     urllib.parse.quote_plus(SQLA_DB_USER),
#     urllib.parse.quote_plus(SQLA_DB_PASSWORD),
#     SQLA_DB_HOST,
#     SQLA_DB_NAME)

**Comment by mijeycgn** [comment]
The solution is very simple. 

SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@{}/{}'.format(
     SQLA_DB_USER,
     SQLA_DB_PASSWORD,
     #urllib.parse.quote_plus(SQLA_DB_USER),
     #urllib.parse.quote_plus(SQLA_DB_PASSWORD),
     SQLA_DB_HOST,
     SQLA_DB_NAME
)

just replace booth lines with urlib.parse [...] with the variables for username and password, then it works fine, if you want to use mysql for instance.
