### ISSUE TITLE
Fresh install, can't upgrade db

### ISSUE THREAD

**Issue by lgwapnitsky** [PowerDNS-Admin/PowerDNS-Admin#1363]
I'm doing a reinstall on one of my boxes to the latest version. I've copied the steps for an install directly (cut/paste) so that they match, but am encountering the following errors:

```
(venv) root@ns1:/opt/web/powerdns-admin# flask db upgrade
Error: While importing 'powerdnsadmin', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/opt/web/powerdns-admin/powerdnsadmin/__init__.py", line 4, in <module>
    from flask_mail import Mail
ModuleNotFoundError: No module named 'flask_mail'


Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'db'.
```

I've declared my ENV variables as such:

```
(venv) root@ns1:/opt/web/powerdns-admin# export | grep -i flask
declare -x FLASK_APP="powerdnsadmin/__init__.py"
declare -x FLASK_CONF="../configs/production.py"
(venv) root@ns1:/opt/web/powerdns-admin# 
```

**Comment by lgwapnitsky** [comment]
nevermind...typo in config file - fat fingers
