### ISSUE TITLE
KeyError: 'description'

### ISSUE THREAD

**Issue by 1rV1N-git** [PowerDNS-Admin/PowerDNS-Admin#1364]
I cannot open dashboard
This error appeared after deletion template
```
KeyError
KeyError: 'description'

Traceback (most recent call last)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
return self.app(environ, start_response)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
            return func(*args, **kwargs)
        elif current_app.config.get('LOGIN_DISABLED'):
            return func(*args, **kwargs)
        elif not current_user.is_authenticated:
            return current_app.login_manager.unauthorized()
        return func(*args, **kwargs)
    return decorated_view
 
 
def fresh_login_required(func):
    '''
File "/opt/web/powerdns-admin/powerdnsadmin/routes/dashboard.py", line 192, in dashboard
detailedHistories = convert_histories(history)
File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 864, in convert_histories
                        else: # no changes were found
                                detailedHistories.append(DetailedHistory(histories[i], None))
                        j += 1
 
                else:
                        detailedHistories.append(DetailedHistory(histories[i], None))
        return detailedHistories
 
@admin_bp.route('/history', methods=['GET', 'POST'])
@login_required
@history_access_required
File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 809, in __init__
                        self.detailed_msg = ""
                        # extract_changelogs_from_a_history_entry(changes_set, history, 0)
                elif 'name' in detail_dict.keys() and 'template' in history.msg: # template creation
                        self.detailed_msg = """
                                <table class="table table-bordered table-striped"><tr><td>Template name:</td><td>{0}</td></tr> <tr><td>Description:</td><td>{1}</td></tr></table>
                                """.format(detail_dict['name'], detail_dict['description'])
                elif 'Change domain' in history.msg and 'access control' in history.msg: # added or removed a user from a domain
                        self.detailed_msg = """
                        <table class="table table-bordered table-striped"><tr><td>Users with access to this domain</td><td>{0}</td></tr><tr><td>Number of users:</td><td>{1}</td><tr></table>
                                """.format(str(detail_dict['user_has_access']).replace("]","").replace("[", ""), len((detail_dict['user_has_access'])))
                elif 'Created API key' in history.msg or 'Updated API key' in history.msg:
```

after clear this row in table history I can open dashboard
Deleted domain template basic_template_1	{'name': 'basic_template_1'}
Deleted domain template basic_template_2	{'name': 'basic_template_2'}
Deleted domain template basic_template_3	{'name': 'basic_template_3'}

**Comment by AzorianMatt** [comment]
@1rV1N-git Please provide what PDA version you are using and what deployment method (bare metal vs Docker). From what I can tell, you're using an older version that is no longer supported.

**Comment by 1rV1N-git** [comment]
baremetal
https://github.com/PowerDNS-Admin/PowerDNS-Admin/commit/701a442d126ebd816d2a9728dba5d3a306ba0efb

**Comment by AzorianMatt** [comment]
@1rV1N-git What about the app version?

**Comment by 1rV1N-git** [comment]
```
[root@DNS-A powerdns-admin]# git show
commit 701a442d126ebd816d2a9728dba5d3a306ba0efb (HEAD -> master)
Author: Dominic Zöller <zoeller@freinet.de>
Date:   Wed Nov 10 11:29:01 2021 +0100

```

**Comment by AzorianMatt** [comment]
@1rV1N-git my bad, I'm just waking up so I didn't even notice the commit tag you originally provided.

So this version is fairly far off from the current 0.3.0 release. Please consider upgrading to that release as issues from older releases will not be maintained at this point due to a lack of contributors. I wish I could promise more support than that, but it's just not realistic right now. I can confirm that I do not have this problem in my currently running 0.3.0 instances as I just deleted those same template records last night in one of them.

**Comment by 1rV1N-git** [comment]
I think it is too old version 
I will try to update
Thank you

**Comment by AzorianMatt** [comment]
@1rV1N-git you're welcome and thank you for being a PDA user!
