### ISSUE TITLE
render_as_batch breaks with Flask-Migrate 4.0+

### ISSUE THREAD

**Issue by Flakebi** [PowerDNS-Admin/PowerDNS-Admin#1376]
Hi,
Flask-Migrate 4.0.0 enables `render_as_batch` by default ([this commit](https://github.com/miguelgrinberg/Flask-Migrate/commit/a3085b34e5b1865d2b773248b37468764df7c312)).
This creates problems with powerdns-admin, which explicitly sets `render_as_batch` [here](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/c5b9e2460498e28baad214afc8c9217a25d1f4d5/migrations/env.py#L76), resulting in it being defined twice:
```
Traceback (most recent call last):
  File "/nix/store/6zc4ndjjdy5avjdah69xrg62w57dg9a7-python3.10-flask-2.2.2/bin/.flask-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/6zc4ndjjdy5avjdah69xrg62w57dg9a7-python3.10-flask-2.2.2/lib/python3.10/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/6zc4ndjjdy5avjdah69xrg62w57dg9a7-python3.10-flask-2.2.2/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/ma613y2nc2fgvj707iyxq666vkfxky04-python3.10-Flask-Migrate-4.0.2/lib/python3.10/site-packages/flask_migrate/cli.py", line 150, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/nix/store/ma613y2nc2fgvj707iyxq666vkfxky04-python3.10-Flask-Migrate-4.0.2/lib/python3.10/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/nix/store/ma613y2nc2fgvj707iyxq666vkfxky04-python3.10-Flask-Migrate-4.0.2/lib/python3.10/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/nix/store/v8798r63vj441ff5a0qwis9935k2ccf2-python3.10-alembic-1.9.1/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/nix/store/v8798r63vj441ff5a0qwis9935k2ccf2-python3.10-alembic-1.9.1/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/nix/store/v8798r63vj441ff5a0qwis9935k2ccf2-python3.10-alembic-1.9.1/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/nix/store/v8798r63vj441ff5a0qwis9935k2ccf2-python3.10-alembic-1.9.1/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/pgb5hwvs9ns4kxbz6anzbk7w12qbmv97-powerdns-admin-0.3.0/share/migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "/nix/store/pgb5hwvs9ns4kxbz6anzbk7w12qbmv97-powerdns-admin-0.3.0/share/migrations/env.py", line 73, in run_migrations_online
    context.configure(connection=connection,
TypeError: alembic.context.configure() got multiple values for keyword argument 'render_as_batch'
```

**Comment by Flakebi** [comment]
This problem still exists and we carry a downstream patch in NixOS: https://github.com/NixOS/nixpkgs/blob/b8c07d634a51d3bba89de755f5693ba77607c40b/pkgs/applications/networking/powerdns-admin/default.nix#L86-L87
