### ISSUE TITLE
An error occurs during Digest authentication.

### ISSUE THREAD

**Issue by harappa** [PowerDNS-Admin/PowerDNS-Admin#1424]
An error occurs if the http request header contains a Digest Authentication style Authorization header.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1432, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/app/powerdnsadmin/routes/base.py", line 34, in handle_internal_server_error
    return render_template('errors/500.html', code=500, message=e), 500
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 153, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 750, in update_template_context
    context.update(func())
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 407, in _user_context_processor
    return dict(current_user=_get_user())
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/usr/lib/python3.10/site-packages/flask_login/login_manager.py", line 378, in _load_user
    user = self._load_user_from_request(request)
  File "/usr/lib/python3.10/site-packages/flask_login/login_manager.py", line 441, in _load_user_from_request
    user = self._request_callback(request)
  File "/app/powerdnsadmin/routes/base.py", line 67, in login_via_authorization_header_or_remote_user
    auth_header = str(base64.b64decode(auth_header), 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 3: invalid start byte
```

An example client request header during Digest authentication is shown below.
```
Authorization: Digest username="Mufasa",
    realm="testrealm@host.com",
    nonce="dcd98b7102dd2f0e8b11d0f600bfb0c093",
    uri="/dir/index.html",
    qop=auth,
    nc=00000001,
    cnonce="0a4f113b",
    response="6629fae49393a05397450978507c4ef1",
    opaque="5ccc069c403ebaf9f0171e9517f40e41"
```

I don't think it's compatible with Digest authentication style Authorization header.
[https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/powerdnsadmin/routes/base.py#L59](url)

**Comment by nkukard** [comment]
Digest authentication cannot be supported as is at present. We're storing the users salted hashed password. Digest authentication would require us to store it in a way we can decrypt it.

ref: https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/04399bd2e121f8f0bff34360af74978920ba9096/src/flask_httpauth.py#L353-L380

I'd say this issue can be closed with "won't fix".

**Comment by nkukard** [comment]
Another exception can be triggered similar to #1447 using the same fuzzed string...
```
curl -L --verbose  -H "Authorization: Basic QkhwbmZqblJKTlB3M3I0"  -X GET  "http://localhost:9080/dashboard"
```

result...
```
powerdnsadmin-test-powerdnsadmin-1  | Traceback (most recent call last):
powerdnsadmin-test-powerdnsadmin-1  |   File "/usr/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 55, in handle
powerdnsadmin-test-powerdnsadmin-1  |     self.handle_request(listener_name, req, client, addr)
powerdnsadmin-test-powerdnsadmin-1  |   File "/usr/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
powerdnsadmin-test-powerdnsadmin-1  |     super().handle_request(listener_name, req, sock, addr)
powerdnsadmin-test-powerdnsadmin-1  |   File "/usr/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
powerdnsadmin-test-powerdnsadmin-1  |     respiter = self.wsgi(environ, resp.start_response)
powerdnsadmin-test-powerdnsadmin-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 2091, in __call__
powerdnsadmin-test-powerdnsadmin-1  |     return self.wsgi_app(environ, start_response)
powerdnsadmin-test-powerdnsadmin-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
powerdnsadmin-test-powerdnsadmin-1  |     return self.app(environ, start_response)
powerdnsadmin-test-powerdnsadmin-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 2076, in wsgi_app
powerdnsadmin-test-powerdnsadmin-1  |     response = self.handle_exception(e)
powerdnsadmin-test-powerdnsadmin-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1432, in handle_exception
powerdnsadmin-test-powerdnsadmin-1  |     server_error = self.ensure_sync(handler)(server_error)
powerdnsadmin-test-powerdnsadmin-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/powerdnsadmin/routes/base.py", line 34, in handle_internal_server_error
powerdnsadmin-test-powerdnsadmin-1  |     return render_template('errors/500.html', code=500, message=e), 500
powerdnsadmin-test-powerdnsadmin-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask/templating.py", line 153, in render_template
powerdnsadmin-test-powerdnsadmin-1  |     ctx.app.update_template_context(context)
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 750, in update_template_context
powerdnsadmin-test-powerdnsadmin-1  |     context.update(func())
powerdnsadmin-test-powerdnsadmin-1  |                    ^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 407, in _user_context_processor
powerdnsadmin-test-powerdnsadmin-1  |     return dict(current_user=_get_user())
powerdnsadmin-test-powerdnsadmin-1  |                              ^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 372, in _get_user
powerdnsadmin-test-powerdnsadmin-1  |     current_app.login_manager._load_user()
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 378, in _load_user
powerdnsadmin-test-powerdnsadmin-1  |     user = self._load_user_from_request(request)
powerdnsadmin-test-powerdnsadmin-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/.venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 441, in _load_user_from_request
powerdnsadmin-test-powerdnsadmin-1  |     user = self._request_callback(request)
powerdnsadmin-test-powerdnsadmin-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  |   File "/app/powerdnsadmin/routes/base.py", line 68, in login_via_authorization_header_or_remote_user
powerdnsadmin-test-powerdnsadmin-1  |     username, password = auth_header.split(":")
powerdnsadmin-test-powerdnsadmin-1  |     ^^^^^^^^^^^^^^^^^^
powerdnsadmin-test-powerdnsadmin-1  | ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by nkukard** [comment]
@AzorianMatt Digest authentication requires us knowing what the user password is, which we don't. So this can be closed now, my previous MR's referenced fix the exceptions.

**Comment by AzorianMatt** [comment]
@nkukard thank you for your work on this! Very thorough!
