### ISSUE TITLE
Powerdns-Admin 0.4.0 OpenID Connect OAuth error

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [PowerDNS-Admin/PowerDNS-Admin#1458]
Hello, 

Trying the new release on my Lab, I also face an issue with our company OpenID OAuth link : 

the error : 

```
Mar 17 14:30:42 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]: [2023-03-17 14:30:42 +0000] [50233] [INFO] Booting worker with pid: 50233
Mar 17 14:30:42 di-css-fe-powerdns-primary-cs-01 gunicorn[50236]: [2023-03-17 14:30:42 +0000] [50236] [INFO] Booting worker with pid: 50236
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]: [2023-03-17 14:37:10,171] [app.py:1449] ERROR - Exception on /oidc/authorized [GET]
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]: Traceback (most recent call last):
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/integrations/base_client/sync_openid.py", line 40, in load_key
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     return jwk_set.find_by_kid(header.get('kid'))
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/jose/rfc7517/key_set.py", line 29, in find_by_kid
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     raise ValueError('Invalid JSON Web Key Set')
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]: ValueError: Invalid JSON Web Key Set
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]: During handling of the above exception, another exception occurred:
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]: Traceback (most recent call last):
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     response = self.full_dispatch_request()
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     rv = self.handle_user_exception(e)
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     rv = self.dispatch_request()
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/powerdnsadmin/services/oidc.py", line 35, in oidc_authorized
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     token = oidc.authorize_access_token()
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     claims = _jwt.decode(
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     data = self._jws.deserialize_compact(s, load_key, decode_payload)
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     key = key(header, payload)
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/integrations/base_client/sync_openid.py", line 44, in load_key
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     return jwk_set.find_by_kid(header.get('kid'))
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:   File "/opt/web/powerdns-admin/PowerDNS-Admin-0.4.0/flask/lib/python3.8/site-packages/authlib/jose/rfc7517/key_set.py", line 29, in find_by_kid
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]:     raise ValueError('Invalid JSON Web Key Set')
Mar 17 14:37:10 di-css-fe-powerdns-primary-cs-01 gunicorn[50233]: ValueError: Invalid JSON Web Key Set
```

After some research, it seems to be related to this issues : 

[https://github.com/lepture/authlib/issues/222](https://github.com/lepture/authlib/issues/222)   and/or  [https://github.com/lepture/authlib/issues/462](https://github.com/lepture/authlib/issues/462)  

Best regards,

**Comment by AzorianMatt** [comment]
@WhatshallIbreaktoday will you do me a favor and try configuring the newly added Metadata URL setting in the app for your specific OAuth provider? There was another recent issue (not exactly the same) which was resolved once applying the use of the Metadata URL setting for the OAuth provider. I'm just curious if it would resolve this issue as well.

Thanks for the report!

**Comment by WhatshallIbreaktoday** [comment]
The first error message I encountered was indeed that the metadata url was missing.
The error I face now is after adding the metadata url.
I'll check next week with my company colleges if we can dig deeper on this issue.

**Comment by mrinc** [comment]
@WhatshallIbreaktoday - Please try do the same as (https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1419#issuecomment-1474541092) but for your oauth server.

It is possible the openid-config url might be diff for you, so you can try `{server}/.well-known/oauth-authorization-server` - and validate it works.

**Comment by WhatshallIbreaktoday** [comment]
Hello,
After some digging with  the Authorization server team, we switched the algo.. and everything came back on track.

Sorry for the disturbance.
Best regards,
