### ISSUE TITLE
docker container crashloops "(MySQLdb._exceptions.OperationalError) (1060, "Duplicate column name 'confirmed'")"

### ISSUE THREAD

**Issue by dmagyar** [PowerDNS-Admin/PowerDNS-Admin#1464]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

Using official docker container: powerdnsadmin/pda-legacy
Empty MySQL database, Flask starts DB migration:

```
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Context impl MySQLImpl.
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 59729e468045 -> 1274ed462010, Change setting.value data type
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 1274ed462010 -> 4a666113c7bb, Adding Operator Role
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 4a666113c7bb -> 31a4ed468b18, Remove all setting in the DB
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 31a4ed468b18 -> 654298797277, Upgrade DB Schema
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 654298797277 -> 0fb6d23a4863, Remove user avatar
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade 856bb94b7040 -> b0fea72a3f20, Update domain serial columns type
Mar 18 22:18:54 crystal docker[334722]: INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column
Mar 18 22:18:54 crystal docker[334722]: ERROR [root] Error: All MySQL CHANGE/MODIFY COLUMN operations require the existing type.
Mar 18 22:18:54 crystal systemd[1]: powerdns-admin.service: Main process exited, code=exited, status=1/FAILURE
```

Then when the container restarts it keeps on crashing:
```
Mar 18 22:19:01 crystal docker[335065]: INFO  [alembic.runtime.migration] Context impl MySQLImpl.
Mar 18 22:19:01 crystal docker[335065]: INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Mar 18 22:19:01 crystal docker[335065]: INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column
Mar 18 22:19:01 crystal docker[335065]: Traceback (most recent call last):
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Mar 18 22:19:01 crystal docker[335065]:     self.dialect.do_execute(
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Mar 18 22:19:01 crystal docker[335065]:     cursor.execute(statement, parameters)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
Mar 18 22:19:01 crystal docker[335065]:     res = self._query(query)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
Mar 18 22:19:01 crystal docker[335065]:     db.query(q)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/MySQLdb/connections.py", line 259, in query
Mar 18 22:19:01 crystal docker[335065]:     _mysql.connection.query(self, query)
Mar 18 22:19:01 crystal docker[335065]: MySQLdb._exceptions.OperationalError: (1060, "Duplicate column name 'confirmed'")
Mar 18 22:19:01 crystal docker[335065]: The above exception was the direct cause of the following exception:
Mar 18 22:19:01 crystal docker[335065]: Traceback (most recent call last):
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/bin/flask", line 8, in <module>
Mar 18 22:19:01 crystal docker[335065]:     sys.exit(main())
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/flask/cli.py", line 986, in main
Mar 18 22:19:01 crystal docker[335065]:     cli.main()
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/flask/cli.py", line 567, in main
Mar 18 22:19:01 crystal docker[335065]:     return super().main(*args, **kwargs)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
Mar 18 22:19:01 crystal docker[335065]:     rv = self.invoke(ctx)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
Mar 18 22:19:01 crystal docker[335065]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
Mar 18 22:19:01 crystal docker[335065]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
Mar 18 22:19:01 crystal docker[335065]:     return ctx.invoke(self.callback, **ctx.params)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
Mar 18 22:19:01 crystal docker[335065]:     return __callback(*args, **kwargs)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
Mar 18 22:19:01 crystal docker[335065]:     return f(get_current_context(), *args, **kwargs)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/flask/cli.py", line 407, in decorator
Mar 18 22:19:01 crystal docker[335065]:     return __ctx.invoke(f, *args, **kwargs)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
Mar 18 22:19:01 crystal docker[335065]:     return __callback(*args, **kwargs)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/flask_migrate/cli.py", line 134, in upgrade
Mar 18 22:19:01 crystal docker[335065]:     _upgrade(directory, revision, sql, tag, x_arg)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/flask_migrate/__init__.py", line 96, in wrapped
Mar 18 22:19:01 crystal docker[335065]:     f(*args, **kwargs)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/flask_migrate/__init__.py", line 271, in upgrade
Mar 18 22:19:01 crystal docker[335065]:     command.upgrade(config, revision, sql=sql, tag=tag)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
Mar 18 22:19:01 crystal docker[335065]:     script.run_env()
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
Mar 18 22:19:01 crystal docker[335065]:     util.load_python_file(self.dir, "env.py")
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
Mar 18 22:19:01 crystal docker[335065]:     module = load_module_py(module_id, path)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
Mar 18 22:19:01 crystal docker[335065]:     spec.loader.exec_module(module)  # type: ignore
Mar 18 22:19:01 crystal docker[335065]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Mar 18 22:19:01 crystal docker[335065]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Mar 18 22:19:01 crystal docker[335065]:   File "/app/migrations/env.py", line 88, in <module>
Mar 18 22:19:01 crystal docker[335065]:     run_migrations_online()
Mar 18 22:19:01 crystal docker[335065]:   File "/app/migrations/env.py", line 81, in run_migrations_online
Mar 18 22:19:01 crystal docker[335065]:     context.run_migrations()
Mar 18 22:19:01 crystal docker[335065]:   File "<string>", line 8, in run_migrations
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
Mar 18 22:19:01 crystal docker[335065]:     self.get_context().run_migrations(**kw)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
Mar 18 22:19:01 crystal docker[335065]:     step.migration_fn(**kw)
Mar 18 22:19:01 crystal docker[335065]:   File "/app/migrations/versions/3f76448bb6de_add_user_confirmed_column.py", line 19, in upgrade
Mar 18 22:19:01 crystal docker[335065]:     with op.batch_alter_table('user') as batch_op:
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
Mar 18 22:19:01 crystal docker[335065]:     next(self.gen)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/operations/base.py", line 383, in batch_alter_table
Mar 18 22:19:01 crystal docker[335065]:     impl.flush()
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/operations/batch.py", line 113, in flush
Mar 18 22:19:01 crystal docker[335065]:     fn(*arg, **kw)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/ddl/impl.py", line 322, in add_column
Mar 18 22:19:01 crystal docker[335065]:     self._exec(base.AddColumn(table_name, column, schema=schema))
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
Mar 18 22:19:01 crystal docker[335065]:     return conn.execute(  # type: ignore[call-overload]
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
Mar 18 22:19:01 crystal docker[335065]:     return meth(self, multiparams, params)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
Mar 18 22:19:01 crystal docker[335065]:     return connection._execute_ddl(self, multiparams, params)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
Mar 18 22:19:01 crystal docker[335065]:     ret = self._execute_context(
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
Mar 18 22:19:01 crystal docker[335065]:     self._handle_dbapi_exception(
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
Mar 18 22:19:01 crystal docker[335065]:     util.raise_(
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Mar 18 22:19:01 crystal docker[335065]:     raise exception
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Mar 18 22:19:01 crystal docker[335065]:     self.dialect.do_execute(
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Mar 18 22:19:01 crystal docker[335065]:     cursor.execute(statement, parameters)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
Mar 18 22:19:01 crystal docker[335065]:     res = self._query(query)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
Mar 18 22:19:01 crystal docker[335065]:     db.query(q)
Mar 18 22:19:01 crystal docker[335065]:   File "/usr/lib/python3.10/site-packages/MySQLdb/connections.py", line 259, in query
Mar 18 22:19:01 crystal docker[335065]:     _mysql.connection.query(self, query)
Mar 18 22:19:01 crystal docker[335065]: sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1060, "Duplicate column name 'confirmed'")
Mar 18 22:19:01 crystal docker[335065]: [SQL: ALTER TABLE user ADD COLUMN confirmed BOOL]
Mar 18 22:19:01 crystal docker[335065]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
Mar 18 22:19:02 crystal systemd[1]: powerdns-admin.service: Main process exited, code=exited, status=1/FAILURE
```

### Expected Behavior

It does not crash loop :)

### Observed Behavior

Crashes on DB field duplication error

**Comment by AzorianMatt** [comment]
@dmagyar thank you for the report. This actually just came up yesterday during a different matter and a fix has been pushed to the dev branch.

You can expect this to make the next patch release `0.4.1`>

**Comment by dmagyar** [comment]
Thank you. I'm eagerly waiting for the release. When will the docker containers be updated?

**Comment by AzorianMatt** [comment]
@dmagyar you're welcome! The containers are updated anything their associated GitHub repository branch is updated. Ergo, the `0.4`, `0`, `master`, and `latest` tags will be updated upon the next release of `0.4.1` later this month, hopefully. Additionally, at that time a new tag of `0.4.1` will be created to reflect this release.

In the mean time, we do have a `dev` tag that will already contain the update if you want to switch to that.
