### ISSUE TITLE
Microsoft OAuth Broken on upgrade to v0.4.0

### ISSUE THREAD

**Issue by danpoltawski** [PowerDNS-Admin/PowerDNS-Admin#1489]
### PDA version

0.4.0

### Python version

3.10

### Steps to Reproduce

1. Configure Powerdns-Admin with official container for v0.3.0
2. Configure Microsoft OAuth Authentication
3. Upgrade to v0.4.0 image

### Expected Behavior

Authentication continues to work

### Observed Behavior

Upon clicking the sign in to Azure:

> HTTP 500 Error  Oops! Something went wrong.

Error logs say:

RuntimeError: Missing "jwks_uri" in metadata

```
2023-03-29T08:30:09+01:00	RuntimeError: Missing "jwks_uri" in metadata
2023-03-29T08:30:09+01:00	    raise RuntimeError('Missing "jwks_uri" in metadata')
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 14, in fetch_jwk_set
2023-03-29T08:30:09+01:00	    jwk_set = JsonWebKey.import_key_set(self.fetch_jwk_set())
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 38, in load_key
2023-03-29T08:30:09+01:00	    key = key(header, payload)
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
2023-03-29T08:30:09+01:00	    algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
2023-03-29T08:30:09+01:00	    data = self._jws.deserialize_compact(s, load_key, decode_payload)
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
2023-03-29T08:30:09+01:00	    claims = _jwt.decode(
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
2023-03-29T08:30:09+01:00	    userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
2023-03-29T08:30:09+01:00	    token = azure.authorize_access_token()
2023-03-29T08:30:09+01:00	  File "/app/powerdnsadmin/services/azure.py", line 35, in azure_authorized
2023-03-29T08:30:09+01:00	    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
2023-03-29T08:30:09+01:00	    rv = self.dispatch_request()
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
2023-03-29T08:30:09+01:00	    rv = self.handle_user_exception(e)
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
2023-03-29T08:30:09+01:00	    response = self.full_dispatch_request()
2023-03-29T08:30:09+01:00	  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
2023-03-29T08:30:09+01:00	Traceback (most recent call last):
2023-03-29T08:30:09+01:00	[2023-03-29 07:30:09,806] [app.py:1449] ERROR - Exception on /azure/authorized [GET]
````

**Comment by danpoltawski** [comment]
Closing as looks a dupe of https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1430
