### ISSUE TITLE
azure auth error missing jwks_uri

### ISSUE THREAD

**Issue by chriss-de** [PowerDNS-Admin/PowerDNS-Admin#1509]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

1. Configure login via azure
2. get error because metadata is missing jwks_uri

### Expected Behavior

get logged in ;)

### Observed Behavior

server error 500

[2023-04-06 12:00:00,518] [app.py:1449] ERROR - Exception on /azure/authorized [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/powerdnsadmin/services/azure.py", line 35, in azure_authorized
    token = azure.authorize_access_token()
  File "/usr/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
    userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
  File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
    claims = _jwt.decode(
  File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
    data = self._jws.deserialize_compact(s, load_key, decode_payload)
  File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
    algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
  File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
    key = key(header, payload)
  File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 38, in load_key
    jwk_set = JsonWebKey.import_key_set(self.fetch_jwk_set())
  File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 14, in fetch_jwk_set
    raise RuntimeError('Missing "jwks_uri" in metadata')
RuntimeError: Missing "jwks_uri" in metadata

**Comment by AzorianMatt** [comment]
@chriss-de did you read the contribution guidelines before submitting this?
