### ISSUE TITLE
Error 500 after upgrading from v0.4.0 to v0.4.1

### ISSUE THREAD

**Issue by gbarre** [PowerDNS-Admin/PowerDNS-Admin#1519]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

1. running powerdnsadmin/pda-legacy:v0.4.1 with docker
2. login using oidc account
3. open a zone
4. error 500

### Expected Behavior

1. running powerdnsadmin/pda-legacy:v0.4.1 with docker
2. login using oidc account
3. open a zone
4. see all records

### Observed Behavior

Everythings works fine with v0.4.0, this happens after upgrading v0.4.1 (just change the docker tag).

Here is the docker log :

```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-04-12 08:06:24 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-04-12 08:06:24 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2023-04-12 08:06:24 +0000] [1] [INFO] Using worker: sync
[2023-04-12 08:06:24 +0000] [8] [INFO] Booting worker with pid: 8
[2023-04-12 08:06:24 +0000] [9] [INFO] Booting worker with pid: 9
[2023-04-12 08:06:24 +0000] [10] [INFO] Booting worker with pid: 10
[2023-04-12 08:06:24 +0000] [11] [INFO] Booting worker with pid: 11
[2023-04-12 08:06:48,512] [app.py:1449] ERROR - Exception on /domain/anonymous.com [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/powerdnsadmin/decorators.py", line 75, in decorated_function
    return f(*args, **kwargs)
  File "/app/powerdnsadmin/routes/domain.py", line 73, in domain
    records_allow_to_edit = Setting().get_records_allow_to_edit()
  File "/app/powerdnsadmin/models/setting.py", line 586, in get_records_allow_to_edit
    set(self.get_forward_records_allow_to_edit() +
  File "/app/powerdnsadmin/models/setting.py", line 590, in get_forward_records_allow_to_edit
    records = self.get('forward_records_allow_edit')
  File "/app/powerdnsadmin/models/setting.py", line 565, in get
    return self.convert_type(setting, result)
  File "/app/powerdnsadmin/models/setting.py", line 481, in convert_type
    return json.loads(value)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)```

**Comment by danpoltawski** [comment]
Would be relaly nice to tag this 0.4.2 rather than hide the issue.

**Comment by AzorianMatt** [comment]
@danpoltawski the release hasn't even aged by a matter of hours at this point. I'm not rolling another version over such a small fix.

To assert that this is "hiding the issue" is outright rude when considering that I didn't wipe out the report, I didn't delete your unnecessary comment, or do anything else that lacks transparency for that matter.

In the future, if you want to make assertions like that, I recommend you take them elsewhere because the next one results in a ban of your GitHub username on this organization.

**Comment by gbarre** [comment]
@AzorianMatt It works ! Thanks :)

**Comment by AzorianMatt** [comment]
@gbarre you're welcome and thank you for the fast report!

Admittedly, I've been really pressed on time so I have rushed many things which has obviously resulted in some mistakes.
