### ISSUE TITLE
Internal server error after session expitres (docker container 0.4.1)

### ISSUE THREAD

**Issue by dangeratgit** [PowerDNS-Admin/PowerDNS-Admin#1560]
### PDA version

0.4.1

### Python version

3.1

### Steps to Reproduce

1. Login autodns
2. Wait until session expires
3. page shows Internal server error

### Expected Behavior

Redirect to login page

### Observed Behavior

` File "/usr/lib/python3.10/site-packages/flask_session/sessions.py", line 535, in open_session
    if saved_session and saved_session.expiry <= datetime.utcnow():
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'
[2023-05-02 11:10:24 +0000] [68534] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2072, in wsgi_app
    ctx.push()
  File "/usr/lib/python3.10/site-packages/flask/ctx.py", line 434, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/usr/lib/python3.10/site-packages/flask_session/sessions.py", line 535, in open_session
    if saved_session and saved_session.expiry <= datetime.utcnow():
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1432, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/app/powerdnsadmin/routes/base.py", line 34, in handle_internal_server_error
    return render_template('errors/500.html', code=500, message=e), 500
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 153, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 750, in update_template_context
    context.update(func())
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 407, in _user_context_processor
    return dict(current_user=_get_user())
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/usr/lib/python3.10/site-packages/flask_login/login_manager.py", line 362, in _load_user
    user_id = session.get("_user_id")
AttributeError: 'NoneType' object has no attribute 'get'
[2023-05-02 11:10:24 +0000] [68534] [DEBUG] GET /favicon.ico
[2023-05-02 11:10:24 +0000] [68534] [ERROR] Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2072, in wsgi_app
    ctx.push()
  File "/usr/lib/python3.10/site-packages/flask/ctx.py", line 434, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/usr/lib/python3.10/site-packages/flask_session/sessions.py", line 535, in open_session
    if saved_session and saved_session.expiry <= datetime.utcnow():
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'
[2023-05-02 11:10:24,365] [app.py:1449] ERROR - Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2072, in wsgi_app
    ctx.push()
  File "/usr/lib/python3.10/site-packages/flask/ctx.py", line 434, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/usr/lib/python3.10/site-packages/flask_session/sessions.py", line 535, in open_session
    if saved_session and saved_session.expiry <= datetime.utcnow():
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'
[2023-05-02 11:10:24 +0000] [68534] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2072, in wsgi_app
    ctx.push()
  File "/usr/lib/python3.10/site-packages/flask/ctx.py", line 434, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/usr/lib/python3.10/site-packages/flask_session/sessions.py", line 535, in open_session
    if saved_session and saved_session.expiry <= datetime.utcnow():
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1432, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/app/powerdnsadmin/routes/base.py", line 34, in handle_internal_server_error
    return render_template('errors/500.html', code=500, message=e), 500
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 153, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 750, in update_template_context
    context.update(func())
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 407, in _user_context_processor
    return dict(current_user=_get_user())
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/usr/lib/python3.10/site-packages/flask_login/login_manager.py", line 362, in _load_user
    user_id = session.get("_user_id")
AttributeError: 'NoneType' object has no attribute 'get'
[2023-05-02 11:10:33 +0000] [47388] [DEBUG] GET /
[2023-05-02 11:10:33 +0000] [47388] [DEBUG] GET /login`

**Comment by dangeratgit** [comment]
Sorry my mistake in my docker update scripts. Yes you are right version 0.4.0, now we Updateted to 0.4.1 and the

**Comment by seitzbg** [comment]
I am still having this issue even with 0.4.1 and also dev branches.  Do I need to delete/clean something?

**Comment by AzorianMatt** [comment]
@seitzbg try emptying your session table in the database.
