### ISSUE TITLE
Zone rrset changelogs broken after #1507

### ISSUE THREAD

**Issue by meineerde** [PowerDNS-Admin/PowerDNS-Admin#1566]
### PDA version

0.4.1

### Python version

3.7

### Steps to Reproduce

I'm using MySQL as a database in case this matters.

1. Enable DNSSec for a domain. A `history` entry with `detail = NULL` is created in the database.
2. When viewing the history of the domain, an exception occurs:
   ```
   [2023-05-10 11:13:07,472] [app.py:1450] ERROR - Exception on /domain/example.com/changelog [GET]
   Traceback (most recent call last):
     File "/opt/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
       response = self.full_dispatch_request()
     File "/opt/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1519, in full_dispatch_request
       rv = self.handle_user_exception(e)
     File "/opt/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1517, in full_dispatch_request
       rv = self.dispatch_request()
     File "/opt/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1503, in dispatch_request
       return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
     File "/opt/powerdns-admin/flask/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
       return current_app.ensure_sync(func)(*args, **kwargs)
     File "/opt/powerdns-admin/powerdnsadmin/decorators.py", line 75, in decorated_function
       return f(*args, **kwargs)
     File "/opt/powerdns-admin/powerdnsadmin/decorators.py", line 48, in decorated_function
       return f(*args, **kwargs)
     File "/opt/powerdns-admin/powerdnsadmin/routes/domain.py", line 227, in changelog
       changes_set = extract_changelogs_from_history(histories)
     File "/opt/powerdns-admin/powerdnsadmin/routes/admin.py", line 122, in extract_changelogs_from_history
       if "add_rrsets" in entry.detail:
   TypeError: argument of type 'NoneType' is not iterable
   ```

### Expected Behavior

I would like to view the history of the domain.

### Observed Behavior

An Exception is raised:

```
TypeError: argument of type 'NoneType' is not iterable
```

Before #1507, there was code handling this case:

```python
if history_entry.detail is None:
    return
```

but this special case was removed when the pull request was applied.

**Comment by AzorianMatt** [comment]
@meineerde great work on documenting this problem and digging up the solution! I'll review this as soon as time permits and look at getting a quick fix pushed to `dev`.

**Comment by AzorianMatt** [comment]
> bump! cant wait for the next release

> This is strictly against the project's contribution guidelines. I removed your other bump as I will this one as well.
