### ISSUE TITLE
Docker build is failing at pip install step due to PyYAML

### ISSUE THREAD

**Issue by vl-siedge** [PowerDNS-Admin/PowerDNS-Admin#1635]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

1. Clone the repository
2. Run `docker build -t powerdnsadmin -f ./docker/Dockerfile .`
3. Get an error at `pip install step`

### Expected Behavior

build passes without errors

### Observed Behavior

Build fails with following error:

```
[+] Building 25.5s (10/21)                                                                                                                                   docker:default
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 1.45kB                                                                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 3.53kB                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/alpine:3.17                                                                                                         1.5s
 => [stage-1 1/8] FROM docker.io/library/alpine:3.17@sha256:e95676db9e4a4f16f6cc01a8915368f82b018cc07aba951c1bd1db586c081388                                           0.5s
 => => resolve docker.io/library/alpine:3.17@sha256:e95676db9e4a4f16f6cc01a8915368f82b018cc07aba951c1bd1db586c081388                                                   0.0s
 => => sha256:81a4480db344455c6e0dbbca3188962273b5eb5c22efa3fef05824de6048bfa8 528B / 528B                                                                             0.0s
 => => sha256:1f73a9d63274924f077b22c7e5a894667cb6a7073638e7d5df3b43be14d1c9ab 1.47kB / 1.47kB                                                                         0.0s
 => => sha256:4db1b89c0bd13344176ddce2d093b9da2ae58336823ffed2009a7ea4b62d2a95 3.37MB / 3.37MB                                                                         0.2s
 => => sha256:e95676db9e4a4f16f6cc01a8915368f82b018cc07aba951c1bd1db586c081388 1.64kB / 1.64kB                                                                         0.0s
 => => extracting sha256:4db1b89c0bd13344176ddce2d093b9da2ae58336823ffed2009a7ea4b62d2a95                                                                              0.2s
 => [internal] load build context                                                                                                                                      0.1s
 => => transferring context: 3.19MB                                                                                                                                    0.1s
 => [builder  2/10] RUN apk add --no-cache build-base     libffi-dev     libpq-dev     libxml2-dev     mariadb-connector-c-dev     openldap-dev     python3-dev     x  9.8s
 => [stage-1 2/8] RUN apk add --no-cache mariadb-connector-c postgresql-client py3-gunicorn py3-pyldap py3-flask py3-psycopg2 xmlsec tzdata libcap &&     addgroup -S  2.4s
 => [builder  3/10] WORKDIR /build                                                                                                                                     0.0s
 => [builder  4/10] COPY ./requirements.txt /build/requirements.txt                                                                                                    0.0s
 => ERROR [builder  5/10] RUN pip install --upgrade pip &&     pip install --use-pep517 -r requirements.txt                                                           13.7s 
------                                                                                                                                                                      
 > [builder  5/10] RUN pip install --upgrade pip &&     pip install --use-pep517 -r requirements.txt:                                                                       
1.685 Requirement already satisfied: pip in /usr/lib/python3.10/site-packages (22.3.1)                                                                                      
1.869 Collecting pip                                                                                                                                                        
1.943   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)                                                                                                                    
2.056      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 18.9 MB/s eta 0:00:00                                                                                        
2.090 Installing collected packages: pip                                                                                                                                    
2.090   Attempting uninstall: pip                                                                                                                                           
2.091     Found existing installation: pip 22.3.1                                                                                                                           
2.093     Uninstalling pip-22.3.1:
2.242       Successfully uninstalled pip-22.3.1
3.546 Successfully installed pip-23.2.1
3.547 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
4.384 Collecting Authlib==1.2.0 (from -r requirements.txt (line 1))
4.446   Downloading Authlib-1.2.0-py2.py3-none-any.whl (214 kB)
4.476      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.8/214.8 kB 7.8 MB/s eta 0:00:00
4.589 Collecting Flask-Assets==2.0 (from -r requirements.txt (line 2))
4.600   Downloading Flask_Assets-2.0-py3-none-any.whl (8.5 kB)
4.627 Collecting Flask-Login==0.6.2 (from -r requirements.txt (line 3))
4.637   Downloading Flask_Login-0.6.2-py3-none-any.whl (17 kB)
4.663 Collecting Flask-Mail==0.9.1 (from -r requirements.txt (line 4))
4.673   Downloading Flask-Mail-0.9.1.tar.gz (45 kB)
4.682      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 6.8 MB/s eta 0:00:00
4.701   Installing build dependencies: started
6.635   Installing build dependencies: finished with status 'done'
6.637   Getting requirements to build wheel: started
6.819   Getting requirements to build wheel: finished with status 'done'
6.822   Preparing metadata (pyproject.toml): started
7.009   Preparing metadata (pyproject.toml): finished with status 'done'
7.046 Collecting Flask-Migrate==2.5.3 (from -r requirements.txt (line 5))
7.061   Downloading Flask_Migrate-2.5.3-py2.py3-none-any.whl (13 kB)
7.102 Collecting Flask-SQLAlchemy==2.5.1 (from -r requirements.txt (line 6))
7.112   Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
7.221 Collecting Flask-SSLify==0.1.5 (from -r requirements.txt (line 7))
7.232   Downloading Flask-SSLify-0.1.5.tar.gz (3.0 kB)
7.242   Installing build dependencies: started
8.843   Installing build dependencies: finished with status 'done'
8.845   Getting requirements to build wheel: started
9.026   Getting requirements to build wheel: finished with status 'done'
9.028   Preparing metadata (pyproject.toml): started
9.225   Preparing metadata (pyproject.toml): finished with status 'done'
9.347 Collecting Flask-SeaSurf==1.1.1 (from -r requirements.txt (line 8))
9.374   Downloading Flask_SeaSurf-1.1.1-py3-none-any.whl (8.4 kB)
9.397 Collecting Flask-Session==0.4.0 (from -r requirements.txt (line 9))
9.405   Downloading Flask_Session-0.4.0-py2.py3-none-any.whl (7.5 kB)
9.444 Collecting Flask==2.1.3 (from -r requirements.txt (line 10))
9.455   Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
9.462      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 18.9 MB/s eta 0:00:00
9.526 Collecting Jinja2==3.1.2 (from -r requirements.txt (line 11))
9.538   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
9.548      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 18.7 MB/s eta 0:00:00
9.607 Collecting PyYAML==5.4 (from -r requirements.txt (line 12))
9.620   Downloading PyYAML-5.4.tar.gz (174 kB)
9.636      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.8/174.8 kB 13.0 MB/s eta 0:00:00
9.823   Installing build dependencies: started
13.15   Installing build dependencies: finished with status 'done'
13.15   Getting requirements to build wheel: started
13.40   Getting requirements to build wheel: finished with status 'error'
13.41   error: subprocess-exited-with-error
13.41   
13.41   × Getting requirements to build wheel did not run successfully.
13.41   │ exit code: 1
13.41   ╰─> [62 lines of output]
13.41       /tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
13.41       !!
13.41       
13.41               ********************************************************************************
13.41               The license_file parameter is deprecated, use license_files instead.
13.41       
13.41               By 2023-Oct-30, you need to update your project and remove deprecated calls
13.41               or your builds will no longer be supported.
13.41       
13.41               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
13.41               ********************************************************************************
13.41       
13.41       !!
13.41         parsed = self.parsers.get(option_name, lambda x: x)(value)
13.41       running egg_info
13.41       writing lib3/PyYAML.egg-info/PKG-INFO
13.41       writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
13.41       writing top-level names to lib3/PyYAML.egg-info/top_level.txt
13.41       Traceback (most recent call last):
13.41         File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
13.41           main()
13.41         File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
13.41           json_out['return_val'] = hook(**hook_input['kwargs'])
13.41         File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
13.41           return hook(config_settings)
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
13.41           return self._get_build_requires(config_settings, requirements=['wheel'])
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
13.41           self.run_setup()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
13.41           exec(code, locals())
13.41         File "<string>", line 271, in <module>
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
13.41           return distutils.core.setup(**attrs)
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
13.41           return run_commands(dist)
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
13.41           dist.run_commands()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
13.41           self.run_command(cmd)
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
13.41           super().run_command(command)
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
13.41           cmd_obj.run()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
13.41           self.find_sources()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
13.41           mm.run()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
13.41           self.add_defaults()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
13.41           sdist.add_defaults(self)
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
13.41           super().add_defaults()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
13.41           self._add_defaults_ext()
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
13.41           self.filelist.extend(build_ext.get_source_files())
13.41         File "<string>", line 201, in get_source_files
13.41         File "/tmp/pip-build-env-dtv9f0g8/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
13.41           raise AttributeError(attr)
13.41       AttributeError: cython_sources
13.41       [end of output]
13.41   
13.41   note: This error originates from a subprocess, and is likely not a problem with pip.
13.41 error: subprocess-exited-with-error
13.41 
13.41 × Getting requirements to build wheel did not run successfully.
13.41 │ exit code: 1
13.41 ╰─> See above for output.
13.41 
13.41 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:33
--------------------
  32 |     # Get application dependencies
  33 | >>> RUN pip install --upgrade pip && \
  34 | >>>     pip install --use-pep517 -r requirements.txt
  35 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --upgrade pip &&     pip install --use-pep517 -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by kolonuk** [comment]
Also to note, this issue is present when building for fresh Debian 12 with PowerDNS installed also, nothing else.

**Comment by garry-a** [comment]
https://github.com/yaml/pyyaml/issues/601
Updating requirements.txt by changing the required version of PyYAML to a minimum of 6.0.1 fixes this issue

**Comment by rbgtk** [comment]
Thanks @garry-a

**Comment by andersonit** [comment]
This is still failing when manually installing without docker and checking out with git.  I manually updated the requirements.txt file with the recommendation above, but could you please update the repo?  Thanks!

**Comment by AzorianMatt** [comment]
This issue has been fixed by updating the project requirements to use PyYAML 6.0.1.

The resolution is now present in the `dev` branch as well as the `powerdnsadmin/pda-legacy:dev` image.
