### ISSUE TITLE
Cannot install required libraries for PowerDNS-Admin on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by samis2613** [PowerDNS-Admin/PowerDNS-Admin#1652]
### PDA version

0.4.1

### Python version

3.10

### Steps to Reproduce

1. git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git /var/www/html/pdns
2. cd /var/www/html/pdns/
3. virtualenv -p python3 flask
4. source ./flask/bin/activate
5. pip install --upgrade pip
6. pip install -r requirements.txt

### Expected Behavior

Install required dependencies without any errors

### Observed Behavior

Collecting Authlib==1.2.0 (from -r requirements.txt (line 1))
  Using cached Authlib-1.2.0-py2.py3-none-any.whl (214 kB)
Collecting Flask-Assets==2.0 (from -r requirements.txt (line 2))
  Using cached Flask_Assets-2.0-py3-none-any.whl (8.5 kB)
Collecting Flask-Login==0.6.2 (from -r requirements.txt (line 3))
  Using cached Flask_Login-0.6.2-py3-none-any.whl (17 kB)
Collecting Flask-Mail==0.9.1 (from -r requirements.txt (line 4))
  Using cached Flask-Mail-0.9.1.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask-Migrate==2.5.3 (from -r requirements.txt (line 5))
  Using cached Flask_Migrate-2.5.3-py2.py3-none-any.whl (13 kB)
Collecting Flask-SQLAlchemy==2.5.1 (from -r requirements.txt (line 6))
  Using cached Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
Collecting Flask-SSLify==0.1.5 (from -r requirements.txt (line 7))
  Using cached Flask-SSLify-0.1.5.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask-SeaSurf==1.1.1 (from -r requirements.txt (line 8))
  Using cached Flask_SeaSurf-1.1.1-py3-none-any.whl (8.4 kB)
Collecting Flask-Session==0.4.0 (from -r requirements.txt (line 9))
  Using cached Flask_Session-0.4.0-py2.py3-none-any.whl (7.5 kB)
Collecting Flask==2.1.3 (from -r requirements.txt (line 10))
  Using cached Flask-2.1.3-py3-none-any.whl (95 kB)
Collecting Jinja2==3.1.2 (from -r requirements.txt (line 11))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting PyYAML==5.4 (from -r requirements.txt (line 12))
  Using cached PyYAML-5.4.tar.gz (174 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/var/www/html/pdns/flask/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/var/www/html/pdns/flask/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/var/www/html/pdns/flask/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in run
          self.find_sources()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
          mm.run()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-bm8wuckb/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by samis2613** [comment]
Figured out a workaround by just downgrading to PyYAML==5.3.1 in requirements.txt
