### ISSUE TITLE
Viewing zone changelog results in HTTP 500 error

### ISSUE THREAD

**Issue by bab5470** [PowerDNS-Admin/PowerDNS-Admin#1674]
### PDA version

0.4.1

### Python version

3.9

### Steps to Reproduce

1. Open a zone
2. Click on change log button in the upper right hand corner
3. Get this error:
"HTTP 500 Error
 Oops! Something went wrong.
Try again later. You may return to the dashboard."

Is there some way I can get powerdns-admin to output the error instead of showing a generic error page?

### Expected Behavior

I should see the change log for the zone

### Observed Behavior

I get an HTTP 500 error instead

**Comment by jspaans91** [comment]
I've the same issue as described in this issue. The issue occurs only when I try to open the change log for zones with DNSSEC enabled.

It results in the following error trace in the log:

`2023-09-27T14:24:29.742970387Z: [ERROR]  [2023-09-27 14:24:29,687] [app.py:1449] ERROR - Exception on /domain/test.nl/changelog [GET]
2023-09-27T14:24:29.743024388Z: [ERROR]  Traceback (most recent call last):
2023-09-27T14:24:29.743030188Z: [ERROR]    File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
2023-09-27T14:24:29.743033888Z: [ERROR]      response = self.full_dispatch_request()
2023-09-27T14:24:29.743037188Z: [ERROR]    File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
2023-09-27T14:24:29.743040488Z: [ERROR]      rv = self.handle_user_exception(e)
2023-09-27T14:24:29.743043688Z: [ERROR]    File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
2023-09-27T14:24:29.743047088Z: [ERROR]      rv = self.dispatch_request()
2023-09-27T14:24:29.743050088Z: [ERROR]    File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
2023-09-27T14:24:29.743053288Z: [ERROR]      return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2023-09-27T14:24:29.743056388Z: [ERROR]    File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
2023-09-27T14:24:29.743059588Z: [ERROR]      return current_app.ensure_sync(func)(*args, **kwargs)
2023-09-27T14:24:29.743062588Z: [ERROR]    File "/app/powerdnsadmin/decorators.py", line 75, in decorated_function
2023-09-27T14:24:29.743065888Z: [ERROR]      return f(*args, **kwargs)
2023-09-27T14:24:29.743068789Z: [ERROR]    File "/app/powerdnsadmin/decorators.py", line 48, in decorated_function
2023-09-27T14:24:29.743071989Z: [ERROR]      return f(*args, **kwargs)
2023-09-27T14:24:29.743074889Z: [ERROR]    File "/app/powerdnsadmin/routes/domain.py", line 227, in changelog
2023-09-27T14:24:29.743078089Z: [ERROR]      changes_set = extract_changelogs_from_history(histories)
2023-09-27T14:24:29.743081089Z: [ERROR]    File "/app/powerdnsadmin/routes/admin.py", line 122, in extract_changelogs_from_history
2023-09-27T14:24:29.743084289Z: [ERROR]      if "add_rrsets" in entry.detail:
2023-09-27T14:24:29.743087389Z: [ERROR]  TypeError: argument of type 'NoneType' is not iterable`

**Comment by maksonlee** [comment]
Have same issue on Dokcer image powerdnsadmin/pda-legacy:latest, tried to enable and disable DNSSEC, show 'Zone Changelog', then got the following error,

```
powerdns_admin  | [2023-11-18 00:33:17 +0000] [10] [ERROR] Exception on /domain/test.com/changelog [GET]
powerdns_admin  | Traceback (most recent call last):
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
powerdns_admin  |     response = self.full_dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
powerdns_admin  |     rv = self.handle_user_exception(e)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
powerdns_admin  |     rv = self.dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
powerdns_admin  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
powerdns_admin  |     return current_app.ensure_sync(func)(*args, **kwargs)
powerdns_admin  |   File "/app/powerdnsadmin/decorators.py", line 75, in decorated_function
powerdns_admin  |     return f(*args, **kwargs)
powerdns_admin  |   File "/app/powerdnsadmin/decorators.py", line 48, in decorated_function
powerdns_admin  |     return f(*args, **kwargs)
powerdns_admin  |   File "/app/powerdnsadmin/routes/domain.py", line 227, in changelog
powerdns_admin  |     changes_set = extract_changelogs_from_history(histories)
powerdns_admin  |   File "/app/powerdnsadmin/routes/admin.py", line 122, in extract_changelogs_from_history
powerdns_admin  |     if "add_rrsets" in entry.detail:
powerdns_admin  | TypeError: argument of type 'NoneType' is not iterable
powerdns_admin  | [2023-11-18 00:33:17,466] [app.py:1449] ERROR - Exception on /domain/test.com/changelog [GET]
powerdns_admin  | Traceback (most recent call last):
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
powerdns_admin  |     response = self.full_dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
powerdns_admin  |     rv = self.handle_user_exception(e)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
powerdns_admin  |     rv = self.dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
powerdns_admin  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
powerdns_admin  |     return current_app.ensure_sync(func)(*args, **kwargs)
powerdns_admin  |   File "/app/powerdnsadmin/decorators.py", line 75, in decorated_function
powerdns_admin  |     return f(*args, **kwargs)
powerdns_admin  |   File "/app/powerdnsadmin/decorators.py", line 48, in decorated_function
powerdns_admin  |     return f(*args, **kwargs)
powerdns_admin  |   File "/app/powerdnsadmin/routes/domain.py", line 227, in changelog
powerdns_admin  |     changes_set = extract_changelogs_from_history(histories)
powerdns_admin  |   File "/app/powerdnsadmin/routes/admin.py", line 122, in extract_changelogs_from_history
powerdns_admin  |     if "add_rrsets" in entry.detail:
powerdns_admin  | TypeError: argument of type 'NoneType' is not iterable
```

**Comment by AzorianMatt** [comment]
@bab5470 please provide very specific steps and environmental information to reproduce this. I am currently unable to reproduce this with the `dev` branch of the project.

**Comment by npdgm** [comment]
I'm experiencing the same issue on 0.4.2:
```
[2024-10-31 22:43:47 +0000] [8] [DEBUG] GET /domain/example.com/changelog
[2024-10-31 22:43:47 +0000] [8] [ERROR] Exception on /domain/example.com/changelog [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/powerdnsadmin/decorators.py", line 79, in decorated_function
    return f(*args, **kwargs)
  File "/app/powerdnsadmin/decorators.py", line 51, in decorated_function
    return f(*args, **kwargs)
  File "/app/powerdnsadmin/routes/domain.py", line 227, in changelog
    changes_set = extract_changelogs_from_history(histories)
  File "/app/powerdnsadmin/routes/admin.py", line 159, in extract_changelogs_from_history
    changes.append(HistoryRecordEntry(entry, rrset, {}, "-"))
  File "/app/powerdnsadmin/routes/admin.py", line 194, in __init__
    self.changeSet = get_record_changes(del_rrset, add_rrset)
  File "/app/powerdnsadmin/routes/admin.py", line 80, in get_record_changes
    del_records = get_records(del_rrset)
  File "/app/powerdnsadmin/routes/admin.py", line 56, in get_records
    records = [dict(record) for record in rrset['records']]
TypeError: 'NoneType' object is not iterable
```

It is triggered by a single TXT RR deletion throught the API proxy and a PDA token, using [go-powerdns](https://github.com/joeig/go-powerdns) as a client:
```go
pdnsErr = pdns.Records.Delete(pdnsCtx, "example.com", "stuff.example.com", powerdns.RRTypeTXT)
```
When this call is made PDA would log the following:
```
[2024-10-31 22:50:43 +0000] [9] [DEBUG] PATCH /api/v1/servers/localhost/zones/example.com.
[2024-10-31 22:50:43 +0000] [9] [DEBUG] Sending request to powerdns API {'rrsets': [{'name': 'stuff.example.com.', 'type': 'TXT', 'changetype': 'DELETE', 'records': None}]}
[2024-10-31 22:50:43,778] [helper.py:18] DEBUG - Sending request to powerdns API {'rrsets': [{'name': 'stuff.example.com.', 'type': 'TXT', 'changetype': 'DELETE', 'records': None}]}
```

Record creations by the API client  won't trigger any changelog bug, it will show new events issued by this PDA token. But once a single deletion is sent throught the PDA API - properly reflected to the zone - any attempt to open the changelog will trigger this trace.
Restarting the app doesn't help, and I could not find any way to restore the changelog after having a quick look at the Sqlite DB. It's not affecting any other function of PDA, and the API keeps serving clients for the affected zone.

**Comment by npdgm** [comment]
I eventually kept cleaning up the `history` table and it fixed the changelog page.
This was the last removed row that kept triggering the 500:
```
698|Apply record changes to zone example.com|{"domain": "example.com", "add_rrsets": [], "del_rrsets": [{"name": "stuff.example.com.", "type": "TXT", "changetype": "DELETE", "records": null}]}|bot token|2024-10-31 22:28:43.493915|26
```

**Comment by WhatshallIbreaktoday** [comment]
can be fixed by simply replacing `if not rrset or 'records' not in rrset:` by `if not rrset or 'records' not in rrset or rrset['records'] is None:` in https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/6b73b8ff08f5b1a2c473089ca9d495261e4169b5/powerdnsadmin/routes/admin.py#L54 in case someone is interested
