### ISSUE TITLE
PowerdnsAdmin and CockroachDB compatibility

### ISSUE THREAD

**Issue by Anghille** [PowerDNS-Admin/PowerDNS-Admin#1687]
### PDA version

I'm Not Sure

### Python version

3.10

### Steps to Reproduce

1. Clone powerdns admin repository
2. Change `Pyyaml`from version `5.4`to `6.0.1`to avoid `Cython_version` error
3. Add `sqlalchemy-cockroachdb==2.0.1` for cockroachDB compatibility
4. Add `SQLALCHEMY_DATABASE_URI=cockroachdb://<user>:<password>@<roach-host>:26257/<database>?sslmode=require&sslrootcert=/certs/ca.crt` to the `docker-compose.yml` environment variable
5. Remote the `image` and add a `build context Dockerfile` to docker-compose (running powerdns admin on rapsberrypi ARM architecture, therefore I must build the image for this architecture at run)
6. Image is correctly build, but got an error at runtime

### Expected Behavior

The container should correctly do the migration steps using alembic, and setup the `setting` database correctly, whatever the database behind might be.

### Observed Behavior

# Steps

1. Clone powerdns admin repository
2. Change `Pyyaml`from version `5.4`to `6.0.1`to avoid `Cython_version` error
3. Add `sqlalchemy-cockroachdb==2.0.1` for cockroachDB compatibility
4. Add `SQLALCHEMY_DATABASE_URI=cockroachdb://<user>:<password>@<roach-host>:26257/<database>?sslmode=require&sslrootcert=/certs/ca.crt` to the `docker-compose.yml` environment variable
5. Remote the `image` and add a `build context Dockerfile` to docker-compose (running powerdns admin on rapsberrypi ARM architecture, therefore I must build the image for this architecture at run)
6. Image is correctly build, but got an error at runtime

# Cockroach

I followed the steps from the official cockroach documentation to setup the database using docker, as well as this medium article to be sure to setup the certificates correctly: https://medium.com/rahasak/deploy-ssl-enabled-cockroachdb-cluster-on-docker-cc2e41108a6b. The database itself has 3 nodes names `cockroach{1,2, 3}`, with `ssl`enabled (certs generated with `cockroach certs` CLI). 

```yaml
version: '3.8'
services:
  cockroach1:
      image: cockroachdb/cockroach:latest
      container_name: cockroach1
      hostname: cockroach1
      volumes:
        - '$COCKROACH1_DATA_DIR:/cockroach/cockroach-data'
        - '$COCKROACH1_CERTS_DIR:/certs'
      ports:
        - "26257:26257"
        - "8080:8080"
      command: "start --certs-dir=/certs --store=cockroach1 --advertise-addr=${COCKROACH1_HOST}:26257 --join=${COCKROACH1_HOST}:26257"


  cockroach2:
      image: cockroachdb/cockroach:latest
      container_name: cockroach2
      hostname: cockroach2
      volumes:
        - '$COCKROACH2_DATA_DIR:/cockroach/cockroach-data'
        - '$COCKROACH2_CERTS_DIR:/certs'
      ports:
        - "26258:26257"
        - "8081:8080"
      command: "start --certs-dir=/certs --store=cockroach2 --advertise-addr=${COCKROACH2_HOST}:26258 --join=${COCKROACH1_HOST}:26257"


  cockroach3:
      image: cockroachdb/cockroach:latest
      container_name: cockroach3
      hostname: cockroach3
      volumes:
        - '$COCKROACH3_DATA_DIR:/cockroach/cockroach-data'
        - '$COCKROACH3_CERTS_DIR:/certs'
      ports:
        - "26259:26257"
        - "8082:8080"
      command: "start --certs-dir=/certs --store=cockroach3 --advertise-addr=${COCKROACH3_HOST}:26259 --join=${COCKROACH1_HOST}:26257"
```

---

The `cockroachDB` database `pdns_admin` content once `powerdns-admin` container is started: 

```bash
  Schema |            Name             | Type  | Owner |         Table
---------+-----------------------------+-------+-------+-------------------------
  public | account                     | table | pdns  | NULL
  public | account_pkey                | index | pdns  | account
  public | account_user                | table | pdns  | NULL
  public | account_user_pkey           | index | pdns  | account_user
  public | alembic_version             | table | pdns  | NULL
  public | alembic_version_pkc         | index | pdns  | alembic_version
  public | domain                      | table | pdns  | NULL
  public | domain_pkey                 | index | pdns  | domain
  public | domain_setting              | table | pdns  | NULL
  public | domain_setting_pkey         | index | pdns  | domain_setting
  public | domain_template             | table | pdns  | NULL
  public | domain_template_pkey        | index | pdns  | domain_template
  public | domain_template_record      | table | pdns  | NULL
  public | domain_template_record_pkey | index | pdns  | domain_template_record
  public | domain_user                 | table | pdns  | NULL
  public | domain_user_pkey            | index | pdns  | domain_user
  public | history                     | table | pdns  | NULL
  public | history_pkey                | index | pdns  | history
  public | ix_account_name             | index | pdns  | account
  public | ix_domain_name              | index | pdns  | domain
  public | ix_domain_template_name     | index | pdns  | domain_template
  public | ix_role_name                | index | pdns  | role
  public | ix_user_username            | index | pdns  | user
  public | role                        | table | pdns  | NULL
  public | role_pkey                   | index | pdns  | role
  public | sessions                    | table | pdns  | NULL
  public | sessions_pkey               | index | pdns  | sessions
  public | sessions_session_id_key     | index | pdns  | sessions
  public | setting                     | table | pdns  | NULL
  public | setting_pkey                | index | pdns  | setting
  public | user                        | table | pdns  | NULL
  public | user_pkey                   | index | pdns  | user
```

---
Content of table `pdns_admin.setting`: 

```sql
USE pdns_admin;
SELECT * FROM setting;  
``` 
```bash                                                                                                              
  id |           name            | value | 
-----+---------------------------+-------+
   1 | maintenance               | False | 
   2 | fullscreen_layout         | True  | 
   3 | record_helper             | True  | 
   4 | login_ldap_first          | True  | 
   5 | default_record_table_size |    15 | 
   6 | default_domain_table_size |    10 | 
   7 | auto_ptr                  | False | 
```

# Powerdns Admin

Docker-compose: 
```yaml 
version: "3.8"
services:
  gui:
    container_name: gui
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - API_KEY=changeme
      - SQLALCHEMY_DATABASE_URI=cockroachdb://<user>:<pwd>@cockroach1:26257/pdns_admin?sslmode=require&sslrootcert=/certs/ca.crt
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
    networks:
      - roachnet
    volumes:
      - "/certs/ca.crt:/certs/ca.crt"

networks:
  roachnet:
    external: true
    name: cockroach_default
```

---

The error when the container starts:
```bash
INFO  [alembic.runtime.migration] Context impl CockroachDBImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "view" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/flask/cli.py", line 986, in main
    cli.main()
  File "/usr/lib/python3.10/site-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/flask/cli.py", line 407, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/lib/python3.10/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/lib/python3.10/site-packages/alembic/command.py", line 398, in upgrade
    script.run_env()
  File "/usr/lib/python3.10/site-packages/alembic/script/base.py", line 579, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "/app/migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python3.10/site-packages/alembic/runtime/environment.py", line 938, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/app/migrations/versions/59729e468045_add_view_column_to_setting_table.py", line 78, in upgrade
    update_data()
  File "/app/migrations/versions/59729e468045_add_view_column_to_setting_table.py", line 28, in update_data
    op.execute(
  File "<string>", line 8, in execute
  File "<string>", line 3, in execute
  File "/usr/lib/python3.10/site-packages/alembic/operations/ops.py", line 2521, in execute
    return operations.invoke(op)
  File "/usr/lib/python3.10/site-packages/alembic/operations/base.py", line 393, in invoke
    return fn(self, operation)
  File "/usr/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 221, in execute_sql
    operations.migration_context.impl.execute(
  File "/usr/lib/python3.10/site-packages/alembic/ddl/impl.py", line 207, in execute
    self._exec(sql, execution_options)
  File "/usr/lib/python3.10/site-packages/alembic/ddl/impl.py", line 200, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "view" does not exist

[SQL: UPDATE setting SET "view"=%(view)s WHERE setting.id <= %(id_1)s]
[parameters: {'view': 'basic', 'id_1': 7}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

What I tried: 

1. Create the column with `ALTER TABLE setting ADD COLUMN "view" VARCHAR(64);`

Result> The specific error disappear but when restarting the container with `docker compose up -d --force-recreate`, I got an new error: 

```bash
INFO  [alembic.runtime.migration] Context impl CockroachDBImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateColumn: column "view" of relation "setting" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/flask/cli.py", line 986, in main
    cli.main()
  File "/usr/lib/python3.10/site-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/flask/cli.py", line 407, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/lib/python3.10/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/lib/python3.10/site-packages/alembic/command.py", line 398, in upgrade
    script.run_env()
  File "/usr/lib/python3.10/site-packages/alembic/script/base.py", line 579, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "/app/migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python3.10/site-packages/alembic/runtime/environment.py", line 938, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/app/migrations/versions/59729e468045_add_view_column_to_setting_table.py", line 74, in upgrade
    op.add_column('setting', sa.Column('view', sa.String(length=64), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/lib/python3.10/site-packages/alembic/operations/ops.py", line 2126, in add_column
    return operations.invoke(op)
  File "/usr/lib/python3.10/site-packages/alembic/operations/base.py", line 393, in invoke
    return fn(self, operation)
  File "/usr/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 168, in add_column
    operations.impl.add_column(table_name, column, schema=schema, **kw)
  File "/usr/lib/python3.10/site-packages/alembic/ddl/impl.py", line 327, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/lib/python3.10/site-packages/alembic/ddl/impl.py", line 200, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateColumn) column "view" of relation "setting" already exists
```

I also tried to add the `sqlalchemy.url` parameter in `alembic.ini`,(following how `cockroachdb` set it up in this [example](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy), without any changes in the errors. 

Is there anything I could do to (at least) temporary fix this error? `Powerdns` supports compatibility with `cockroachDB` and I wanted to avoid using multiple databases, which would lead to more components to setup / maintain in the stack :( 

I tried to tackle the code and found the 2 "culprits" here: 

1. https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/migrations/versions/31a4ed468b18_remove_all_settings_in_the_db.py
2. https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/migrations/versions/59729e468045_add_view_column_to_setting_table.py

Apparently, `alembic` can be used with `cockroachDB` ([official migration doc]( https://www.cockroachlabs.com/docs/stable/alembic)) or `sqlalchemy` (see.

**Comment by Anghille** [comment]
PS: Thank you for any support you could provide and for this amazing tool <3

**Comment by AzorianMatt** [comment]
@Anghille I appreciate you providing the effort to work through much of your issue. Unfortunately, the project can not currently prioritize additional database support (regardless if it is supported by SQAlchemy already), as this was never on a road map and there are much higher priorities currently.

I will stash this away for later consideration, but I can not offer any further expectations at this time.

Thanks!
