### ISSUE TITLE
Table initialization problem with utf8mb4 collation/character set in MySQL/MariaDB

### ISSUE THREAD

**Issue by dsgagi** [PowerDNS-Admin/PowerDNS-Admin#316]
`flask db upgrade` step fails if MySQL/MariaDB default database collation is set to `utf8mb4_unicode_ci` and default character set is set to `utf8mb4`.

Error full trace is below.
```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/util/compat.py", line 96, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/opt/web/powerdns-admin/migrations/versions/787bdba9e147_init_db.py", line 83, in upgrade
    op.create_index(op.f('ix_domain_template_name'), 'domain_template', ['name'], unique=True)
  File "<string>", line 8, in create_index
  File "<string>", line 3, in create_index
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/operations/ops.py", line 857, in create_index
    return operations.invoke(op)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/operations/toimpl.py", line 88, in create_index
    operations.impl.create_index(idx)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/ddl/impl.py", line 201, in create_index
    self._exec(schema.CreateIndex(index))
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/ddl/impl.py", line 115, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: 'CREATE UNIQUE INDEX ix_domain_template_name ON domain_template (name)'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by dsgagi** [comment]
Little more info below :)
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by parryjacob** [comment]
A note for anyone else who stumbles upon this: setting `innodb_large_prefix` to `on` in your MariaDB config if you have version 10.x will resolve this issue.

**Comment by Rico29** [comment]
Hello. Tried this, and I still have the problem : 

MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_large%'\G
*************************** 1. row ***************************
Variable_name: innodb_large_prefix
        Value: ON

(flask) root@dns-pdns# flask db upgrade
...
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1709, 'Index column size too large. The maximum column size is 767 bytes.') [SQL: 'CREATE UNIQUE INDEX ix_domain_template_name ON domain_template (name)'] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by mauriciobau** [comment]
> 
> 
> Hello. Tried this, and I still have the problem :
> 
> MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_large%'\G
> *************************** 1. row ***************************
> Variable_name: innodb_large_prefix
> Value: ON
> 
> (flask) root@dns-pdns# flask db upgrade
> ...
> sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1709, 'Index column size too large. The maximum column size is 767 bytes.') [SQL: 'CREATE UNIQUE INDEX ix_domain_template_name ON domain_template (name)'] (Background on this error at: http://sqlalche.me/e/e3q8)

Hi, I'm also having this problem, can anyone solve it or can you give some tips? I already tried to change this in mysql but it did not work.

SET GLOBAL innodb_file_format=Barracuda;
SET GLOBAL innodb_file_per_table=ON;
SET GLOBAL innodb_large_prefix=1;

I'm trying to install on a Debian 9.5 and MariaDB 10

**Comment by Rico29** [comment]
@mauriciobau use mariadb 10.3 from mariadb repos. See : 
https://downloads.mariadb.org/mariadb/repositories/#mirror=ovh&distro=Debian&distro_release=stretch--stretch&version=10.3

**Comment by TacoScheltema** [comment]
For anyone that doesn't have the option upgrading their mariadb version, what fixed it for me is:

`CREATE DATABASE pdnsadmin character set UTF8 collate utf8_bin`
