### ISSUE TITLE
Issues with AD LDAP and ADFS

### ISSUE THREAD

**Issue by MaxDiOrio** [PowerDNS-Admin/PowerDNS-Admin#337]
When I try to log in with a user using AD LDAP, I get a red box: 'LDAP_ADMIN_USERNAME' and nothing happens.   What I really want is User and Admin groups assigned by LDAP group membership.  Do the accounts need to be pre-created, or will it take care of creating the accounts?

LDAP_ENABLED = True
## AD CONFIG
LDAP_TYPE = 'ad'
LDAP_URI = 'ldap://la-2pdom01:389'
LDAP_USERNAME = 'CN=SVC_LDAP_RO,OU=General,OU=Service,OU=Accounts,DC=internal,DC=domain,DC=com'
LDAP_PASSWORD = 'password'
LDAP_SEARCH_BASE = 'DC=internal,DC=domain,DC=com'
## You may prefer 'userPrincipalName' instead
LDAP_USERNAMEFIELD = 'sAMAccountName'
## AD Group that you would like to have accesss to web app
#LDAP_FILTER = 'CN=PowerDNS_Users,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com'
LDAP_FILTER = '(objectClass=user)'
LDAP_GROUP_SECURITY = True # True or False
LDAP_ADMIN_GROUP = 'CN=PowerDNS_Admins,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=ieeeglobalspec,DC=com'
LDAP_USER_GROUP = 'CN=PowerDNS_Users,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=ieeeglobalspec,DC=com'

ALSO
Does anyone have a clue how to get ADFS working properly with this?  We really need a WIKI article, and by rights, LDAP and ADFS should be integrated into the admin UI configuration with test buttons.

**Comment by MaxDiOrio** [comment]
I'll tag on to this - I think I have it almost working properly now.  Turns out your config-template.py appears to be wrong.  The app is looking for LDAP_ADMIN_USERNAME as the attribute to search the ldap directory.  The config-template.py doesn't have this variable in there, it uses LDAP_USERNAME.  I copied the template out of development.py and am using that with appropriate changes.

But now I'm getting:  2018-08-21 16:42:16,593 - app.models - ERROR - User mdiorio is not part of the "CN=PowerDNS_Admins,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com" or "CN=PowerDNS_Users,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com" groups that allow access to PowerDNS-Admin

I believe this is the same as #335

Here's my new setup that at least is getting me most of the way there.  I believe LDAP_FILTER should just filter for any user, then let the LDAP_GROUP_SECURITY section handle which group to put them in.  If they don't fall into either group, they should be getting denied access.

But why isn't it looking up group membership correctly?  I'm guessing there's a missing field needed for AD group membership.  Something like here in my Rancher config.  I feel like it's not search with distinguishedName which AD uses for group membership.

![image](https://user-images.githubusercontent.com/25855524/44428680-28397680-a563-11e8-9aeb-78d2aaecd11a.png)


> # LDAP CONFIG
> LDAP_ENABLED = True
> LDAP_ADMIN_USERNAME = 'CN=SVC_LDAP_RO,OU=General,OU=Service,OU=Accounts,DC=internal,DC=domain,DC=com'
> LDAP_ADMIN_PASSWORD = 'password'
> LDAP_GROUP_SECURITY = True # True or False
> LDAP_ADMIN_GROUP = 'CN=PowerDNS_Admins,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com'
> LDAP_USER_GROUP = 'CN=PowerDNS_Users,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com'
> 
> ## AD CONFIG
> LDAP_TYPE = 'ad'
> LDAP_URI = 'ldaps://la-2pdom01.internal.domain.com:636'
> LDAP_USERNAME = 'CN=SVC_LDAP_RO,OU=General,OU=Service,OU=Accounts,DC=internal,DC=domain,DC=com'
> LDAP_PASSWORD = 'password'
> LDAP_SEARCH_BASE = 'DC=internal,DC=domainc,DC=com'
> ## You may prefer 'userPrincipalName' instead
> LDAP_USERNAMEFIELD = 'sAMAccountName'
> ## AD Group that you would like to have accesss to web app
> LDAP_FILTER = '(&(objectClass=user))'

**Comment by ngoduykhanh** [comment]
Your are right, the`config_template.py` wasn't updated after renaming the variables for LDAP. I am working on branch `app_config_adjustment` to manage all these configs from database side to avoid the outdate. I will also take a look at your AD integration issue. Are you sure that your user is belong to `CN=PowerDNS_Admins,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com` or `CN=PowerDNS_Users,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com`group?

**Comment by MaxDiOrio** [comment]
Yes, absolutely sure. I created the group and added myself to it. I have one account in each of those groups and it give the same error when logging in with either account. I verified the full distinguished name from the AD property.

**Comment by ngoduykhanh** [comment]
The current group filter doesn't work with AD. I did some adjustment on #339 . Can you try it ? It worked fine in my test with Azure AD secure LDAP.

**Comment by MaxDiOrio** [comment]
I pulled #339, which said I needed to do a DB migration.  I started the migration, but it got stuck at INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table

I left it for hours with no change in status, eventually having to kill it and reboot the server.  Upon trying again:

INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1060, "Duplicate column name 'view'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/util/compat.py", line 96, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/opt/web/powerdns-admin/migrations/versions/59729e468045_add_view_column_to_setting_table.py", line 74, in upgrade
    op.add_column('setting', sa.Column('view', sa.String(length=64), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/operations/ops.py", line 1565, in add_column
    return operations.invoke(op)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/operations/toimpl.py", line 123, in add_column
    schema=schema
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/ddl/impl.py", line 169, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/alembic/ddl/impl.py", line 115, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1060, "Duplicate column name 'view'") [SQL: 'ALTER TABLE setting ADD COLUMN view VARCHAR(64)'] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by MaxDiOrio** [comment]
So after a failed DB upgrade, I redeployed everything from scratch using the app_config_adjustment branch, but now getting: 
Traceback (most recent call last):
  File "./run.py", line 3, in <module>
    from config import PORT
ImportError: cannot import name 'PORT'

when trying to do a ./run.py

**Comment by MaxDiOrio** [comment]
Missing the PORT variable in the config.py.    Could I stick with basing my config off of the config_template.py in this branch?

**Comment by MaxDiOrio** [comment]
Good grief - the config_template.py file in this branch doesn't have any LDAP configuration in it at all.  Only SAML.  Getting:
2018-08-22 17:00:17,682 - app.models - WARNING - User "mdiorio" does not exist. Authentication request from 10.85.146.129

**Comment by ngoduykhanh** [comment]
LDAP configuration has been managed in the DB. You have to sign up the first local user to login and configure the LDAP setting at: _Setting > Authentication > LDAP_

**Comment by MaxDiOrio** [comment]
Getting closer!  I can log in with my admin level account via LDAP AD auth and it works fine.  Creates the account in PDNS-Admin as an administrator, perfect.

When I go to log in as a regular user, I'm getting:

2018-08-23 09:28:47,193 - app.models - INFO - User mdiorio is part of the "CN=PowerDNS_Users,OU=Infrastructure,OU=SecurityGroups,DC=internal,DC=domain,DC=com" group that allows user access to PowerDNS-Admin
2018-08-23 09:28:47,204 - app.models - ERROR - {'info': '80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580', 'desc': 'Invalid credentials'}
2018-08-23 09:28:47,204 - app.models - ERROR - User "mdiorio" input a wrong LDAP password. Authentication request from 10.85.146.146

I guarantee with 100% certainty that the password is correct.  I even changed it and tried again, same thing.  I'm not seeing an authentication request come through that DC either, whether it be a success or failure.  There's no attempt to authenticate the account, and definitely no bad password attempt logged in AD.

**Comment by MaxDiOrio** [comment]
So I have had two co-workers try to log in with regular domain accounts and they don't work with the same wrong LDAP password error.  However the logs do show it is pulling the correct user account and matches the user account to the correct security group.

If I log into an account that is a member of the Admins group, it works perfectly fine.

I tried moving the regular account into the Admin's security group, I've tried moving the regular admin account into the same OU as the a- account, nothing works.

It's the strangest thing.

**Comment by ngoduykhanh** [comment]
The code `52e` clearly shows that it was "Invalid credentials" error. If the password is correct, i guess the bind dn was wrong. What did you configure for the `Basic filter` and `Username field` ?

FIYL: I don't know which kind of AD are you using, in my case, i am using Azure AD which requires [Enable password hash synchronization](https://docs.microsoft.com/en-us/azure/active-directory-domain-services/active-directory-ds-getting-started-password-sync) to allow 3rd application authenticate the user with password.

**Comment by MaxDiOrio** [comment]
We're using on-prem AD running on Server 2012.

My bind dn is correct. We use it across the entire org for all our ldap lookups.

Basic filter I used organizationalPerson
Username is sAMAccountName

I have this exact config working in about a dozen other ldap setups without issue.

**Comment by MaxDiOrio** [comment]
Any thoughts on this - we're really close to getting this working?  It's holding up rolling this out to our development team for Kubernetes integration.  Thanks!

**Comment by ngoduykhanh** [comment]
Unfortunately I don't have any idea for this issue at the moment. It looks weird to me too. If you are able to login with some users but not others, so i guess there are differences in your AD user's attributes. You can try to dump your LDAP data to check. 
Also, try with [userPrincipalName](https://docs.microsoft.com/en-us/windows/desktop/ad/naming-properties#userprincipalname) for username field to use full usern

**Comment by MaxDiOrio** [comment]
My LDAP is fine, there really should be no Attributes being read other than UPN, the password, and email.  Not sure why, when I have debugging turned on, it's logging every single AD attribute.  Completely unnecessary.  UPN does the same thing by the way.

**Comment by MaxDiOrio** [comment]
Got it!  The CN for our non-admin level users is CN=Last, First
As soon as I changed the CN to First Last it worked fine.  So whatever the process is doing isn't properly handling the comma in the CN, unlike every other LDAP setup that we've happened to come across.

**Comment by ngoduykhanh** [comment]
So the comma need to be escaped i think. Just a quick test, can you put `\\` in front of commas when login ?

**Comment by MaxDiOrio** [comment]
Changing the CN in Active Directory to escape the comma doesn't help.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
