### ISSUE TITLE
Latest migration changes broke Postgres support

### ISSUE THREAD

**Issue by justjanne** [PowerDNS-Admin/PowerDNS-Admin#635]
Roughly 1.5 months ago, the project ran just fine with postgres as database backend. Due to new migrations which have been added, and relevant changes, this is now broken.

This would be a minor change, being a huge improvement nonetheless.

**Comment by keesbos** [comment]
diff --git a/migrations/versions/3f76448bb6de_add_user_confirmed_column.py b/migrations/versions/3f76448bb6de_add_user_confirmed_column.py
index d1b6d29..490aebe 100644
--- a/migrations/versions/3f76448bb6de_add_user_confirmed_column.py
+++ b/migrations/versions/3f76448bb6de_add_user_confirmed_column.py
@@ -18,8 +18,12 @@ depends_on = None
 def upgrade():
     with op.batch_alter_table('user') as batch_op:
         batch_op.add_column(
-            sa.Column('confirmed', sa.Boolean(), nullable=False,
+            sa.Column('confirmed', sa.Boolean(), nullable=True,
                       default=False))
+    with op.batch_alter_table('user') as batch_op:
+        user = sa.sql.table('user', sa.sql.column('confirmed'))
+        batch_op.execute(user.update().values(confirmed=False))
+        batch_op.alter_column('confirmed', nullable=False)

**Comment by ngoduykhanh** [comment]
Hi,

Can you show your setup and the error message during the migration?
I've tried with PostgreSQL 12 and it looks good to me.

**Comment by keesbos** [comment]
Error:
```
# flask db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 856bb94b7040 -> b0fea72a3f20, Update domain serial columns type
INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column
Traceback (most recent call last):
  File "/opt/powerdns-admin/py-pdns-adm/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/powerdns-admin/py-pdns-adm/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: column "confirmed" contains null values
```
Ubuntu (in lxd container):
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
Postgresql:
```
# dpkg -l | grep postg
ii  postgresql                     10+190ubuntu0.1                    all          object-relational SQL database (supported version)
ii  postgresql-10                  10.10-0ubuntu0.18.04.1             amd64        object-relational SQL database, version 10 server
ii  postgresql-client-10           10.10-0ubuntu0.18.04.1             amd64        front-end programs for PostgreSQL 10
ii  postgresql-client-common       190ubuntu0.1                       all          manager for multiple PostgreSQL client versions
ii  postgresql-common              190ubuntu0.1                       all          PostgreSQL database-cluster manager
```
(Note, the git diff fixes it for me)

It looks like the default value isn't applied to the table with sqlalchemy. With pg_dump:
```
CREATE TABLE public."user" (
    id integer NOT NULL,
    username character varying(64),
    password character varying(64),
    firstname character varying(64),
    lastname character varying(64),
    email character varying(128),
    otp_secret character varying(16),
    role_id integer,
    confirmed boolean NOT NULL
);
```
And no `alter table set default` for the `confirmed` column.

The only `alter table set default` statements I see in then dump are for `nextval()` (i.e. the `id` columns).

**Comment by bjo81** [comment]
Any update on this?

**Comment by halkeye** [comment]
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "confirmed" contains null values                                                                                                                                                                                                                  [SQL: ALTER TABLE "user" ADD COLUMN confirmed BOOLEAN NOT NULL]                                                                                                                                                                                                                                                             
(Background on this error at: http://sqlalche.me/e/13/gkpj)   

So I applied the update manually
```
ALTER TABLE "user" ADD COLUMN confirmed BOOLEAN NOT NULL default false;
update "user" set confirmed=true;
update "alembic_version" set "version_num"='3f76448bb6de';
```

Proper fix:
https://github.com/ngoduykhanh/PowerDNS-Admin/commit/7739bf7cfcc2522934b2f8c80c2805c8902c4a9a#diff-5b6d721374eb2724c78efcc59227e40954dc25bff97a4b6d72123ac5d16cbea2R21 should get a default value to match https://github.com/ngoduykhanh/PowerDNS-Admin/blob/5f10f739ea95f51d539ebd7927d90bba5c5dc7ae/powerdnsadmin/models/user.py#L31

Since i've already applied the migration, I don't have lots of motivation to make a PR.

**Comment by joachimtingvold** [comment]
Same happens with PostgreSQL 13. The patch from @keesbos works, so that can essentially be used as the PR for fixing it (unless someone wants to refine it more).

```(venv) pdnsadmin@dnsadmin1:/srv/vhosts/dnsadmin.foo.bar$ flask db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 654298797277 -> 0fb6d23a4863, Remove user avatar
INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
INFO  [alembic.runtime.migration] Running upgrade 856bb94b7040 -> b0fea72a3f20, Update domain serial columns type
INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column
Traceback (most recent call last):
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: column "confirmed" of relation "user" contains null values


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/vhosts/dnsadmin.foo.bar/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "/srv/vhosts/dnsadmin.foo.bar/migrations/versions/3f76448bb6de_add_user_confirmed_column.py", line 20, in upgrade
    batch_op.add_column(
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/operations/base.py", line 374, in batch_alter_table
    impl.flush()
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/operations/batch.py", line 107, in flush
    fn(*arg, **kw)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 324, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 197, in _exec
    return conn.execute(construct, multiparams)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/srv/vhosts/dnsadmin.foo.bar/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "confirmed" of relation "user" contains null values

[SQL: ALTER TABLE "user" ADD COLUMN confirmed BOOLEAN NOT NULL]```

**Comment by jbe-dw** [comment]
@keesbos I've not checked the migration scripts but it looks to me that it hasn't been fixed. Can you confirm ?

**Comment by jbe-dw** [comment]
Related #787
