### ISSUE TITLE
Sort error

### ISSUE THREAD

**Issue by jonathaanbastin** [PowerDNS-Admin/PowerDNS-Admin#838]
I am seeing an issue when trying to view a domain.

Traceback (most recent call last):
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/powerdnsadmin/flask/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/powerdnsadmin/powerdnsadmin/decorators.py", line 60, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/powerdnsadmin/powerdnsadmin/routes/domain.py", line 60, in domain
    rrsets = Record().get_rrsets(domain.name)
  File "/var/www/powerdnsadmin/powerdnsadmin/models/record.py", line 70, in get_rrsets
    r['records'], r['comments'] = (list(t) for t in zip(*sorted(zip(r['records'], r['comments']), key=by_record_content_pair)))
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
