### ISSUE TITLE
Several UI actions fail with an AJAX error

### ISSUE THREAD

**Issue by wrosenauer** [PowerDNS-Admin/PowerDNS-Admin#973]
Many UI actions in the webinterface fail with such an error:
![grafik](https://user-images.githubusercontent.com/1312102/124887212-40048c00-dfd5-11eb-9cda-0215519f7d1a.png)

The server returns a 500 error code for the action.

The logs show that it seems to be caused by an idna issue:

`[2021-07-08 08:12:30 +0000] [9] [DEBUG] GET /dashboard/domains-custom/reverse
[2021-07-08 08:12:30 +0000] [9] [ERROR] Exception on /dashboard/domains-custom/reverse [GET]
Traceback (most recent call last):
  File "/app/powerdnsadmin/lib/utils.py", line 244, in pretty_domain_name
    return value.encode().decode('idna')
  File "/usr/lib/python3.8/encodings/idna.py", line 214, in decode
    result.append(ToUnicode(label))
  File "/usr/lib/python3.8/encodings/idna.py", line 139, in ToUnicode
    raise UnicodeError("IDNA does not round-trip", label, label2)
UnicodeError: ('IDNA does not round-trip', b'xn--der-grte-vya3u', b'xn--der-grsste-jcb')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/powerdnsadmin/routes/dashboard.py", line 121, in domains_custom
    render.name(domain),
  File "/usr/lib/python3.8/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/app/powerdnsadmin/templates/dashboard_domain.html", line 24, in macro
  File "/app/powerdnsadmin/lib/utils.py", line 246, in pretty_domain_name
    raise Exception("Cannot decode IDN domain")
Exception: Cannot decode IDN domain
[2021-07-08 08:12:30,434] [app.py:1891] ERROR - Exception on /dashboard/domains-custom/reverse [GET]
Traceback (most recent call last):
  File "/app/powerdnsadmin/lib/utils.py", line 244, in pretty_domain_name
    return value.encode().decode('idna')
  File "/usr/lib/python3.8/encodings/idna.py", line 214, in decode
    result.append(ToUnicode(label))
  File "/usr/lib/python3.8/encodings/idna.py", line 139, in ToUnicode
    raise UnicodeError("IDNA does not round-trip", label, label2)
UnicodeError: ('IDNA does not round-trip', b'xn--der-grte-vya3u', b'xn--der-grsste-jcb')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/powerdnsadmin/routes/dashboard.py", line 121, in domains_custom
    render.name(domain),
  File "/usr/lib/python3.8/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/app/powerdnsadmin/templates/dashboard_domain.html", line 24, in macro
  File "/app/powerdnsadmin/lib/utils.py", line 246, in pretty_domain_name
    raise Exception("Cannot decode IDN domain")
Exception: Cannot decode IDN domain
`

**Comment by steschuser** [comment]
Might be related to #935 
`raise UnicodeError("IDNA does not round-trip", label, label2)
UnicodeError: ('IDNA does not round-trip', b'xn--der-grte-vya3u', b'xn--der-grsste-jcb')`

Could you try https://github.com/ngoduykhanh/PowerDNS-Admin/pull/936 ?

If that does not work, could you provide all data of 'xn--der-grsste-jcb' domain?

regards,
Steffen
