### ISSUE TITLE
ERROR - Exception on /oidc/authorized

### ISSUE THREAD

**Issue by huifanglu2018** [PowerDNS-Admin/PowerDNS-Admin#999]
I am using keycloak to auth powerdns admin.
but I get this error in powerdns admin log :
```
[2021-09-02 09:49:43,831] [app.py:1891] ERROR - Exception on /oidc/authorized [GET]
--
Thu, Sep 2 2021 5:49:43 pm | Traceback (most recent call last):
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Thu, Sep 2 2021 5:49:43 pm | response = self.full_dispatch_request()
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Thu, Sep 2 2021 5:49:43 pm | rv = self.handle_user_exception(e)
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Thu, Sep 2 2021 5:49:43 pm | reraise(exc_type, exc_value, tb)
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Thu, Sep 2 2021 5:49:43 pm | raise value
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Thu, Sep 2 2021 5:49:43 pm | rv = self.dispatch_request()
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Thu, Sep 2 2021 5:49:43 pm | return self.view_functions[rule.endpoint](**req.view_args)
Thu, Sep 2 2021 5:49:43 pm | File "/app/powerdnsadmin/services/oidc.py", line 34, in oidc_authorized
Thu, Sep 2 2021 5:49:43 pm | token = oidc.authorize_access_token()
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/authlib/integrations/flask_client/remote_app.py", line 76, in authorize_access_token
Thu, Sep 2 2021 5:49:43 pm | token = self.fetch_access_token(**params)
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/authlib/integrations/base_client/remote_app.py", line 110, in fetch_access_token
Thu, Sep 2 2021 5:49:43 pm | token = client.fetch_token(token_endpoint, **kwargs)
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/authlib/oauth2/client.py", line 203, in fetch_token
Thu, Sep 2 2021 5:49:43 pm | return self._fetch_token(
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/authlib/oauth2/client.py", line 226, in _fetch_token
Thu, Sep 2 2021 5:49:43 pm | return self.parse_response_token(resp.json())
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
Thu, Sep 2 2021 5:49:43 pm | return complexjson.loads(self.text, **kwargs)
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
Thu, Sep 2 2021 5:49:43 pm | return _default_decoder.decode(s)
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
Thu, Sep 2 2021 5:49:43 pm | obj, end = self.raw_decode(s)
Thu, Sep 2 2021 5:49:43 pm | File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
Thu, Sep 2 2021 5:49:43 pm | return self.scan_once(s, idx=_w(s, idx).end())
Thu, Sep 2 2021 5:49:43 pm | simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Thu, Sep 2 2021 5:50:12 pm | [2021-09-02 09:50:12,303] [app.py:1891] ERROR - Exception on /oidc/authorized [GET]
Thu, Sep 2 2021 5:50:12 pm | Traceback (most recent call last):
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Thu, Sep 2 2021 5:50:12 pm | response = self.full_dispatch_request()
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Thu, Sep 2 2021 5:50:12 pm | rv = self.handle_user_exception(e)
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Thu, Sep 2 2021 5:50:12 pm | reraise(exc_type, exc_value, tb)
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Thu, Sep 2 2021 5:50:12 pm | raise value
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Thu, Sep 2 2021 5:50:12 pm | rv = self.dispatch_request()
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Thu, Sep 2 2021 5:50:12 pm | return self.view_functions[rule.endpoint](**req.view_args)
Thu, Sep 2 2021 5:50:12 pm | File "/app/powerdnsadmin/services/oidc.py", line 34, in oidc_authorized
Thu, Sep 2 2021 5:50:12 pm | token = oidc.authorize_access_token()
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/authlib/integrations/flask_client/remote_app.py", line 76, in authorize_access_token
Thu, Sep 2 2021 5:50:12 pm | token = self.fetch_access_token(**params)
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/authlib/integrations/base_client/remote_app.py", line 110, in fetch_access_token
Thu, Sep 2 2021 5:50:12 pm | token = client.fetch_token(token_endpoint, **kwargs)
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/authlib/oauth2/client.py", line 203, in fetch_token
Thu, Sep 2 2021 5:50:12 pm | return self._fetch_token(
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/authlib/oauth2/client.py", line 226, in _fetch_token
Thu, Sep 2 2021 5:50:12 pm | return self.parse_response_token(resp.json())
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
Thu, Sep 2 2021 5:50:12 pm | return complexjson.loads(self.text, **kwargs)
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
Thu, Sep 2 2021 5:50:12 pm | return _default_decoder.decode(s)
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
Thu, Sep 2 2021 5:50:12 pm | obj, end = self.raw_decode(s)
Thu, Sep 2 2021 5:50:12 pm | File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
Thu, Sep 2 2021 5:50:12 pm | return self.scan_once(s, idx=_w(s, idx).end())
Thu, Sep 2 2021 5:50:12 pm | simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
![admin](https://user-images.githubusercontent.com/41109801/131826337-51b4ed58-dcc3-46f1-9493-3ab279c2879a.png)

**Comment by RGanor** [comment]
@huifanglu2018  This issue is still relevant?
